/* Autogenerated file */


#ifndef STGEN_bios_H
#define STGEN_bios_H
#include <stdint.h>

#include "stgen.h"

namespace Bios {


/* Enum BiosOpcode */
enum class BiosOpcode : uint32_t {
	Getmpb               =      0, /*  */
	Bconstat             =      1, /*  */
	Bconin               =      2, /*  */
	Bconout              =      3, /*  */
	Rwabs                =      4, /*  */
	Setexc               =      5, /*  */
	Tickcal              =      6, /*  */
	Getbpb               =      7, /*  */
	Bcostat              =      8, /*  */
	Mediach              =      9, /*  */
	Drvmap               =     10, /*  */
	Kbshift              =     11  /*  */
};

/* Enum -> string lookup declarations */
extern const char* GetString(BiosOpcode val);
extern const char* GetEnumString(BiosOpcode val);

/* Register Addresses */

/* Register Field Accessors */

/* Register Field Sets */

} // namespace
#endif
