/* Autogenerated file */

#include "bios.h"

namespace Bios {

const char* GetString(Opcode val)
{
	if (val==Opcode::Getmpb) return "Get memory parameter block";
	if (val==Opcode::Bconstat) return "Get device input status";
	if (val==Opcode::Bconin) return "Read char from device";
	if (val==Opcode::Bconout) return "Send char to device";
	if (val==Opcode::Rwabs) return "Read/write drive operation";
	if (val==Opcode::Setexc) return "Set/get interrupt vector";
	if (val==Opcode::Tickcal) return "Get timer time difference";
	if (val==Opcode::Getbpb) return "Get bios parameter block";
	if (val==Opcode::Bcostat) return "Get device output status";
	if (val==Opcode::Mediach) return "Check media change";
	if (val==Opcode::Drvmap) return "Get attached device map";
	if (val==Opcode::Kbshift) return "Get/set shift key status";
	return "?";
}
const char* GetEnumString(Opcode val)
{
	if (val==Opcode::Getmpb) return "Getmpb";
	if (val==Opcode::Bconstat) return "Bconstat";
	if (val==Opcode::Bconin) return "Bconin";
	if (val==Opcode::Bconout) return "Bconout";
	if (val==Opcode::Rwabs) return "Rwabs";
	if (val==Opcode::Setexc) return "Setexc";
	if (val==Opcode::Tickcal) return "Tickcal";
	if (val==Opcode::Getbpb) return "Getbpb";
	if (val==Opcode::Bcostat) return "Bcostat";
	if (val==Opcode::Mediach) return "Mediach";
	if (val==Opcode::Drvmap) return "Drvmap";
	if (val==Opcode::Kbshift) return "Kbshift";
	return "?";
}
const stgen::StringDef g_enumDescs_Opcode[] = {
	{ 0, "Get memory parameter block" },
	{ 1, "Get device input status" },
	{ 2, "Read char from device" },
	{ 3, "Send char to device" },
	{ 4, "Read/write drive operation" },
	{ 5, "Set/get interrupt vector" },
	{ 6, "Get timer time difference" },
	{ 7, "Get bios parameter block" },
	{ 8, "Get device output status" },
	{ 9, "Check media change" },
	{ 10, "Get attached device map" },
	{ 11, "Get/set shift key status" },
	{ 0, nullptr }
};
/* Register Field Sets */

} // namespace
