/* Autogenerated file */

#include "bios.h"

namespace Bios {

const char* GetString(BiosOpcode val)
{
	if (val==BiosOpcode::Getmpb) return "";
	if (val==BiosOpcode::Bconstat) return "";
	if (val==BiosOpcode::Bconin) return "";
	if (val==BiosOpcode::Bconout) return "";
	if (val==BiosOpcode::Rwabs) return "";
	if (val==BiosOpcode::Setexc) return "";
	if (val==BiosOpcode::Tickcal) return "";
	if (val==BiosOpcode::Getbpb) return "";
	if (val==BiosOpcode::Bcostat) return "";
	if (val==BiosOpcode::Mediach) return "";
	if (val==BiosOpcode::Drvmap) return "";
	if (val==BiosOpcode::Kbshift) return "";
	return "?";
}
const char* GetEnumString(BiosOpcode val)
{
	if (val==BiosOpcode::Getmpb) return "Getmpb";
	if (val==BiosOpcode::Bconstat) return "Bconstat";
	if (val==BiosOpcode::Bconin) return "Bconin";
	if (val==BiosOpcode::Bconout) return "Bconout";
	if (val==BiosOpcode::Rwabs) return "Rwabs";
	if (val==BiosOpcode::Setexc) return "Setexc";
	if (val==BiosOpcode::Tickcal) return "Tickcal";
	if (val==BiosOpcode::Getbpb) return "Getbpb";
	if (val==BiosOpcode::Bcostat) return "Bcostat";
	if (val==BiosOpcode::Mediach) return "Mediach";
	if (val==BiosOpcode::Drvmap) return "Drvmap";
	if (val==BiosOpcode::Kbshift) return "Kbshift";
	return "?";
}
const stgen::StringDef g_enumDescs_BiosOpcode[] = {
	{ 0, "" },
	{ 1, "" },
	{ 2, "" },
	{ 3, "" },
	{ 4, "" },
	{ 5, "" },
	{ 6, "" },
	{ 7, "" },
	{ 8, "" },
	{ 9, "" },
	{ 10, "" },
	{ 11, "" },
	{ 0, nullptr }
};
/* Register Field Sets */

} // namespace
