/* Autogenerated file */

#include "gemdos.h"

namespace Gemdos {

const char* GetString(GemdosOpcode val)
{
	if (val==GemdosOpcode::Pterm0) return "";
	if (val==GemdosOpcode::Cconin) return "";
	if (val==GemdosOpcode::Cconout) return "";
	if (val==GemdosOpcode::Cauxin) return "";
	if (val==GemdosOpcode::Cauxout) return "";
	if (val==GemdosOpcode::Cprnout) return "";
	if (val==GemdosOpcode::Crawio) return "";
	if (val==GemdosOpcode::Crawcin) return "";
	if (val==GemdosOpcode::Cnecin) return "";
	if (val==GemdosOpcode::Cconws) return "";
	if (val==GemdosOpcode::Cconrs) return "";
	if (val==GemdosOpcode::Cconis) return "";
	if (val==GemdosOpcode::Dsetdrv) return "";
	if (val==GemdosOpcode::Cconos) return "";
	if (val==GemdosOpcode::Cprnos) return "";
	if (val==GemdosOpcode::Cauxis) return "";
	if (val==GemdosOpcode::Cauxos) return "";
	if (val==GemdosOpcode::Maddalt) return "";
	if (val==GemdosOpcode::Srealloc) return "(TOS 4)";
	if (val==GemdosOpcode::Slbopen) return "(MagiC)";
	if (val==GemdosOpcode::Slbclose) return "(MagiC)";
	if (val==GemdosOpcode::Dgetdrv) return "";
	if (val==GemdosOpcode::Fsetdta) return "";
	if (val==GemdosOpcode::Super) return "";
	if (val==GemdosOpcode::Tgetdate) return "";
	if (val==GemdosOpcode::Tsetdate) return "";
	if (val==GemdosOpcode::Tgettime) return "";
	if (val==GemdosOpcode::Tsettime) return "";
	if (val==GemdosOpcode::Fgetdta) return "";
	if (val==GemdosOpcode::Sversion) return "";
	if (val==GemdosOpcode::Ptermres) return "";
	if (val==GemdosOpcode::Sconfig) return "(MagiC)";
	if (val==GemdosOpcode::Dfree) return "";
	if (val==GemdosOpcode::Dcreate) return "";
	if (val==GemdosOpcode::Ddelete) return "";
	if (val==GemdosOpcode::Dsetpath) return "";
	if (val==GemdosOpcode::Fcreate) return "";
	if (val==GemdosOpcode::Fopen) return "";
	if (val==GemdosOpcode::Fclose) return "";
	if (val==GemdosOpcode::Fread) return "";
	if (val==GemdosOpcode::Fwrite) return "";
	if (val==GemdosOpcode::Fdelete) return "";
	if (val==GemdosOpcode::Fseek) return "";
	if (val==GemdosOpcode::Fattrib) return "";
	if (val==GemdosOpcode::Mxalloc) return "";
	if (val==GemdosOpcode::Fdup) return "";
	if (val==GemdosOpcode::Fforce) return "";
	if (val==GemdosOpcode::Dgetpath) return "";
	if (val==GemdosOpcode::Malloc) return "";
	if (val==GemdosOpcode::Mfree) return "";
	if (val==GemdosOpcode::Mshrink) return "";
	if (val==GemdosOpcode::Pexec) return "";
	if (val==GemdosOpcode::Pterm) return "";
	if (val==GemdosOpcode::Fsfirst) return "";
	if (val==GemdosOpcode::Fsnext) return "";
	if (val==GemdosOpcode::Frename) return "";
	if (val==GemdosOpcode::Fdatime) return "";
	if (val==GemdosOpcode::Flock) return "";
	if (val==GemdosOpcode::Nversion) return "";
	if (val==GemdosOpcode::Frlock) return "";
	if (val==GemdosOpcode::Frunlock) return "";
	if (val==GemdosOpcode::F_lock) return "";
	if (val==GemdosOpcode::Funlock) return "";
	if (val==GemdosOpcode::Fflush) return "";
	if (val==GemdosOpcode::Syield) return "(MiNT)";
	if (val==GemdosOpcode::Fpipe) return "(MiNT)";
	if (val==GemdosOpcode::Ffchown) return "(MiNT)";
	if (val==GemdosOpcode::Ffchmod) return "(MiNT)";
	if (val==GemdosOpcode::Fsync) return "(MiNT)";
	if (val==GemdosOpcode::Fcntl) return "(MiNT)";
	if (val==GemdosOpcode::Finstat) return "(MiNT)";
	if (val==GemdosOpcode::Foutstat) return "(MiNT)";
	if (val==GemdosOpcode::Fgetchar) return "(MiNT)";
	if (val==GemdosOpcode::Fputchar) return "(MiNT)";
	if (val==GemdosOpcode::Pwait) return "(MiNT)";
	if (val==GemdosOpcode::Pnice) return "(MiNT)";
	if (val==GemdosOpcode::Pgetpid) return "(MiNT)";
	if (val==GemdosOpcode::Pgetppid) return "(MiNT)";
	if (val==GemdosOpcode::Pgetpgrp) return "(MiNT)";
	if (val==GemdosOpcode::Psetpgrp) return "(MiNT)";
	if (val==GemdosOpcode::Pgetuid) return "(MiNT)";
	if (val==GemdosOpcode::Psetuid) return "(MiNT)";
	if (val==GemdosOpcode::Pkill) return "(MiNT)";
	if (val==GemdosOpcode::Psignal) return "(MiNT)";
	if (val==GemdosOpcode::Pvfork) return "(MiNT)";
	if (val==GemdosOpcode::Pgetgid) return "(MiNT)";
	if (val==GemdosOpcode::Psetgid) return "(MiNT)";
	if (val==GemdosOpcode::Psigblock) return "(MiNT)";
	if (val==GemdosOpcode::Psigsetmask) return "(MiNT)";
	if (val==GemdosOpcode::Pusrval) return "(MiNT)";
	if (val==GemdosOpcode::Pdomain) return "(MiNT)";
	if (val==GemdosOpcode::Psigreturn) return "(MiNT)";
	if (val==GemdosOpcode::Pfork) return "(MiNT)";
	if (val==GemdosOpcode::Pwait3) return "(MiNT)";
	if (val==GemdosOpcode::Fselect) return "(MiNT)";
	if (val==GemdosOpcode::Prusage) return "(MiNT)";
	if (val==GemdosOpcode::Psetlimit) return "(MiNT)";
	if (val==GemdosOpcode::Talarm) return "(MiNT)";
	if (val==GemdosOpcode::Pause) return "(MiNT)";
	if (val==GemdosOpcode::Sysconf) return "(MiNT)";
	if (val==GemdosOpcode::Psigpending) return "MiNT";
	if (val==GemdosOpcode::Dpathconf) return "(MiNT)";
	if (val==GemdosOpcode::Pmsg) return "(MiNT)";
	if (val==GemdosOpcode::Fmidipipe) return "(MiNT)";
	if (val==GemdosOpcode::Prenice) return "(MiNT)";
	if (val==GemdosOpcode::Dopendir) return "(MiNT)";
	if (val==GemdosOpcode::Dreaddir) return "(MiNT)";
	if (val==GemdosOpcode::Drewinddir) return "(MiNT)";
	if (val==GemdosOpcode::Dclosedir) return "(MiNT)";
	if (val==GemdosOpcode::Fxattr) return "(MiNT)";
	if (val==GemdosOpcode::Flink) return "(MiNT)";
	if (val==GemdosOpcode::Fsymlink) return "(MiNT)";
	if (val==GemdosOpcode::Freadlink) return "(MiNT)";
	if (val==GemdosOpcode::Dcntl) return "(MiNT)";
	if (val==GemdosOpcode::Fchown) return "(MiNT)";
	if (val==GemdosOpcode::Fchmod) return "(MiNT)";
	if (val==GemdosOpcode::Pumask) return "(MiNT)";
	if (val==GemdosOpcode::Psemaphore) return "(MiNT)";
	if (val==GemdosOpcode::Dlock) return "(MiNT)";
	if (val==GemdosOpcode::Psigpause) return "(MiNT)";
	if (val==GemdosOpcode::Psigaction) return "(MiNT)";
	if (val==GemdosOpcode::Pgeteuid) return "(MiNT)";
	if (val==GemdosOpcode::Pgetegid) return "(MiNT)";
	if (val==GemdosOpcode::Pwaitpid) return "(MiNT)";
	if (val==GemdosOpcode::Dgetcwd) return "(MiNT)";
	if (val==GemdosOpcode::Salert) return "(MiNT)";
	if (val==GemdosOpcode::Tmalarm) return "(MiNT 1.10)";
	if (val==GemdosOpcode::Psigintr) return "(MiNT 1.11 until FreeMiNT 1.15.12 inclusive)";
	if (val==GemdosOpcode::Suptime) return "(MiNT 1.11)";
	if (val==GemdosOpcode::Ptrace) return "(MiNT)";
	if (val==GemdosOpcode::Mvalidate) return "(MiNT)";
	if (val==GemdosOpcode::Dxreaddir) return "(MiNT 1.11)";
	if (val==GemdosOpcode::Pseteuid) return "(MiNT 1.11)";
	if (val==GemdosOpcode::Psetegid) return "(MiNT 1.11)";
	if (val==GemdosOpcode::Pgetauid) return "(MiNT 1.11)";
	if (val==GemdosOpcode::Psetauid) return "(MiNT 1.11)";
	if (val==GemdosOpcode::Pgetgroups) return "(MiNT 1.11)";
	if (val==GemdosOpcode::Psetgroups) return "(MiNT 1.11)";
	if (val==GemdosOpcode::Tsetitimer) return "(MiNT 1.11)";
	if (val==GemdosOpcode::Scookie) return "(MiNT (obsolete))";
	if (val==GemdosOpcode::Fstat64) return "(MiNT)";
	if (val==GemdosOpcode::Fseek64) return "(MiNT)";
	if (val==GemdosOpcode::Dsetkey) return "(MiNT)";
	if (val==GemdosOpcode::Psetreuid) return "(MiNT 1.12)";
	if (val==GemdosOpcode::Psetregid) return "(MiNT 1.12)";
	if (val==GemdosOpcode::Ssync) return "(MiNT, MagiC)";
	if (val==GemdosOpcode::Shutdown) return "(MiNT)";
	if (val==GemdosOpcode::Dreadlabel) return "(MiNT 1.12)";
	if (val==GemdosOpcode::Dwritelabel) return "MiNT 1.12";
	if (val==GemdosOpcode::Ssystem) return "(MiNT 1.15.0)";
	if (val==GemdosOpcode::Tgettimeofday) return "(MiNT 1.15.0)";
	if (val==GemdosOpcode::Tsettimeofday) return "(MiNT 1.15.0)";
	if (val==GemdosOpcode::Tadjtime) return "(MiNT)";
	if (val==GemdosOpcode::Pgetpriority) return "(MiNT 1.15.0)";
	if (val==GemdosOpcode::Psetpriority) return "(MiNT 1.15.0)";
	if (val==GemdosOpcode::Fpoll) return "(MiNTNet)";
	if (val==GemdosOpcode::Fwritev) return "(MiNTNet)";
	if (val==GemdosOpcode::Freadv) return "(MiNTNet)";
	if (val==GemdosOpcode::Ffstat64) return "(MiNTNet)";
	if (val==GemdosOpcode::Psysctl) return "(MiNT)";
	if (val==GemdosOpcode::Pemulation) return "(MiNT)";
	if (val==GemdosOpcode::Fsocket) return "(MiNTNet)";
	if (val==GemdosOpcode::Fsocketpair) return "(MiNTNet)";
	if (val==GemdosOpcode::Faccept) return "(MiNTNet)";
	if (val==GemdosOpcode::Fconnect) return "(MiNTNet)";
	if (val==GemdosOpcode::Fbind) return "(MiNTNet)";
	if (val==GemdosOpcode::Flisten) return "(MiNTNet)";
	if (val==GemdosOpcode::Frecvmsg) return "(MiNTNet)";
	if (val==GemdosOpcode::Fsendmsg) return "(MiNTNet)";
	if (val==GemdosOpcode::Frecvfrom) return "(MiNTNet)";
	if (val==GemdosOpcode::Fsendto) return "(MiNTNet)";
	if (val==GemdosOpcode::Fsetsockopt) return "(MiNTNet)";
	if (val==GemdosOpcode::Fgetsockopt) return "(MiNTNet)";
	if (val==GemdosOpcode::Fgetpeername) return "(MiNTNet)";
	if (val==GemdosOpcode::Fgetsockname) return "(MiNTNet)";
	if (val==GemdosOpcode::Fshutdown) return "(MiNTNet)";
	if (val==GemdosOpcode::Pshmget) return "(MiNT)";
	if (val==GemdosOpcode::Pshmctl) return "(MiNT)";
	if (val==GemdosOpcode::Pshmat) return "(MiNT)";
	if (val==GemdosOpcode::Pshmdt) return "(MiNT)";
	if (val==GemdosOpcode::Psemget) return "(MiNT)";
	if (val==GemdosOpcode::Psemctl) return "(MiNT)";
	if (val==GemdosOpcode::Psemop) return "(MiNT)";
	if (val==GemdosOpcode::Psemconfig) return "(MiNT)";
	if (val==GemdosOpcode::Pmsgget) return "(MiNT)";
	if (val==GemdosOpcode::Pmsgctl) return "(MiNT)";
	if (val==GemdosOpcode::Pmsgsnd) return "(MiNT)";
	if (val==GemdosOpcode::Pmsgrcv) return "(MiNT)";
	if (val==GemdosOpcode::Maccess) return "(MiNT)";
	if (val==GemdosOpcode::Fchown16) return "(FreeMiNT 1.16.0)";
	if (val==GemdosOpcode::Fchdir) return "(FreeMiNT 1.17)";
	if (val==GemdosOpcode::Ffdopendir) return "(FreeMiNT 1.17)";
	if (val==GemdosOpcode::Fdirfd) return "(FreeMiNT 1.17)";
	return "?";
}
const char* GetEnumString(GemdosOpcode val)
{
	if (val==GemdosOpcode::Pterm0) return "Pterm0";
	if (val==GemdosOpcode::Cconin) return "Cconin";
	if (val==GemdosOpcode::Cconout) return "Cconout";
	if (val==GemdosOpcode::Cauxin) return "Cauxin";
	if (val==GemdosOpcode::Cauxout) return "Cauxout";
	if (val==GemdosOpcode::Cprnout) return "Cprnout";
	if (val==GemdosOpcode::Crawio) return "Crawio";
	if (val==GemdosOpcode::Crawcin) return "Crawcin";
	if (val==GemdosOpcode::Cnecin) return "Cnecin";
	if (val==GemdosOpcode::Cconws) return "Cconws";
	if (val==GemdosOpcode::Cconrs) return "Cconrs";
	if (val==GemdosOpcode::Cconis) return "Cconis";
	if (val==GemdosOpcode::Dsetdrv) return "Dsetdrv";
	if (val==GemdosOpcode::Cconos) return "Cconos";
	if (val==GemdosOpcode::Cprnos) return "Cprnos";
	if (val==GemdosOpcode::Cauxis) return "Cauxis";
	if (val==GemdosOpcode::Cauxos) return "Cauxos";
	if (val==GemdosOpcode::Maddalt) return "Maddalt";
	if (val==GemdosOpcode::Srealloc) return "Srealloc";
	if (val==GemdosOpcode::Slbopen) return "Slbopen";
	if (val==GemdosOpcode::Slbclose) return "Slbclose";
	if (val==GemdosOpcode::Dgetdrv) return "Dgetdrv";
	if (val==GemdosOpcode::Fsetdta) return "Fsetdta";
	if (val==GemdosOpcode::Super) return "Super";
	if (val==GemdosOpcode::Tgetdate) return "Tgetdate";
	if (val==GemdosOpcode::Tsetdate) return "Tsetdate";
	if (val==GemdosOpcode::Tgettime) return "Tgettime";
	if (val==GemdosOpcode::Tsettime) return "Tsettime";
	if (val==GemdosOpcode::Fgetdta) return "Fgetdta";
	if (val==GemdosOpcode::Sversion) return "Sversion";
	if (val==GemdosOpcode::Ptermres) return "Ptermres";
	if (val==GemdosOpcode::Sconfig) return "Sconfig";
	if (val==GemdosOpcode::Dfree) return "Dfree";
	if (val==GemdosOpcode::Dcreate) return "Dcreate";
	if (val==GemdosOpcode::Ddelete) return "Ddelete";
	if (val==GemdosOpcode::Dsetpath) return "Dsetpath";
	if (val==GemdosOpcode::Fcreate) return "Fcreate";
	if (val==GemdosOpcode::Fopen) return "Fopen";
	if (val==GemdosOpcode::Fclose) return "Fclose";
	if (val==GemdosOpcode::Fread) return "Fread";
	if (val==GemdosOpcode::Fwrite) return "Fwrite";
	if (val==GemdosOpcode::Fdelete) return "Fdelete";
	if (val==GemdosOpcode::Fseek) return "Fseek";
	if (val==GemdosOpcode::Fattrib) return "Fattrib";
	if (val==GemdosOpcode::Mxalloc) return "Mxalloc";
	if (val==GemdosOpcode::Fdup) return "Fdup";
	if (val==GemdosOpcode::Fforce) return "Fforce";
	if (val==GemdosOpcode::Dgetpath) return "Dgetpath";
	if (val==GemdosOpcode::Malloc) return "Malloc";
	if (val==GemdosOpcode::Mfree) return "Mfree";
	if (val==GemdosOpcode::Mshrink) return "Mshrink";
	if (val==GemdosOpcode::Pexec) return "Pexec";
	if (val==GemdosOpcode::Pterm) return "Pterm";
	if (val==GemdosOpcode::Fsfirst) return "Fsfirst";
	if (val==GemdosOpcode::Fsnext) return "Fsnext";
	if (val==GemdosOpcode::Frename) return "Frename";
	if (val==GemdosOpcode::Fdatime) return "Fdatime";
	if (val==GemdosOpcode::Flock) return "Flock";
	if (val==GemdosOpcode::Nversion) return "Nversion";
	if (val==GemdosOpcode::Frlock) return "Frlock";
	if (val==GemdosOpcode::Frunlock) return "Frunlock";
	if (val==GemdosOpcode::F_lock) return "F_lock";
	if (val==GemdosOpcode::Funlock) return "Funlock";
	if (val==GemdosOpcode::Fflush) return "Fflush";
	if (val==GemdosOpcode::Syield) return "Syield";
	if (val==GemdosOpcode::Fpipe) return "Fpipe";
	if (val==GemdosOpcode::Ffchown) return "Ffchown";
	if (val==GemdosOpcode::Ffchmod) return "Ffchmod";
	if (val==GemdosOpcode::Fsync) return "Fsync";
	if (val==GemdosOpcode::Fcntl) return "Fcntl";
	if (val==GemdosOpcode::Finstat) return "Finstat";
	if (val==GemdosOpcode::Foutstat) return "Foutstat";
	if (val==GemdosOpcode::Fgetchar) return "Fgetchar";
	if (val==GemdosOpcode::Fputchar) return "Fputchar";
	if (val==GemdosOpcode::Pwait) return "Pwait";
	if (val==GemdosOpcode::Pnice) return "Pnice";
	if (val==GemdosOpcode::Pgetpid) return "Pgetpid";
	if (val==GemdosOpcode::Pgetppid) return "Pgetppid";
	if (val==GemdosOpcode::Pgetpgrp) return "Pgetpgrp";
	if (val==GemdosOpcode::Psetpgrp) return "Psetpgrp";
	if (val==GemdosOpcode::Pgetuid) return "Pgetuid";
	if (val==GemdosOpcode::Psetuid) return "Psetuid";
	if (val==GemdosOpcode::Pkill) return "Pkill";
	if (val==GemdosOpcode::Psignal) return "Psignal";
	if (val==GemdosOpcode::Pvfork) return "Pvfork";
	if (val==GemdosOpcode::Pgetgid) return "Pgetgid";
	if (val==GemdosOpcode::Psetgid) return "Psetgid";
	if (val==GemdosOpcode::Psigblock) return "Psigblock";
	if (val==GemdosOpcode::Psigsetmask) return "Psigsetmask";
	if (val==GemdosOpcode::Pusrval) return "Pusrval";
	if (val==GemdosOpcode::Pdomain) return "Pdomain";
	if (val==GemdosOpcode::Psigreturn) return "Psigreturn";
	if (val==GemdosOpcode::Pfork) return "Pfork";
	if (val==GemdosOpcode::Pwait3) return "Pwait3";
	if (val==GemdosOpcode::Fselect) return "Fselect";
	if (val==GemdosOpcode::Prusage) return "Prusage";
	if (val==GemdosOpcode::Psetlimit) return "Psetlimit";
	if (val==GemdosOpcode::Talarm) return "Talarm";
	if (val==GemdosOpcode::Pause) return "Pause";
	if (val==GemdosOpcode::Sysconf) return "Sysconf";
	if (val==GemdosOpcode::Psigpending) return "Psigpending";
	if (val==GemdosOpcode::Dpathconf) return "Dpathconf";
	if (val==GemdosOpcode::Pmsg) return "Pmsg";
	if (val==GemdosOpcode::Fmidipipe) return "Fmidipipe";
	if (val==GemdosOpcode::Prenice) return "Prenice";
	if (val==GemdosOpcode::Dopendir) return "Dopendir";
	if (val==GemdosOpcode::Dreaddir) return "Dreaddir";
	if (val==GemdosOpcode::Drewinddir) return "Drewinddir";
	if (val==GemdosOpcode::Dclosedir) return "Dclosedir";
	if (val==GemdosOpcode::Fxattr) return "Fxattr";
	if (val==GemdosOpcode::Flink) return "Flink";
	if (val==GemdosOpcode::Fsymlink) return "Fsymlink";
	if (val==GemdosOpcode::Freadlink) return "Freadlink";
	if (val==GemdosOpcode::Dcntl) return "Dcntl";
	if (val==GemdosOpcode::Fchown) return "Fchown";
	if (val==GemdosOpcode::Fchmod) return "Fchmod";
	if (val==GemdosOpcode::Pumask) return "Pumask";
	if (val==GemdosOpcode::Psemaphore) return "Psemaphore";
	if (val==GemdosOpcode::Dlock) return "Dlock";
	if (val==GemdosOpcode::Psigpause) return "Psigpause";
	if (val==GemdosOpcode::Psigaction) return "Psigaction";
	if (val==GemdosOpcode::Pgeteuid) return "Pgeteuid";
	if (val==GemdosOpcode::Pgetegid) return "Pgetegid";
	if (val==GemdosOpcode::Pwaitpid) return "Pwaitpid";
	if (val==GemdosOpcode::Dgetcwd) return "Dgetcwd";
	if (val==GemdosOpcode::Salert) return "Salert";
	if (val==GemdosOpcode::Tmalarm) return "Tmalarm";
	if (val==GemdosOpcode::Psigintr) return "Psigintr";
	if (val==GemdosOpcode::Suptime) return "Suptime";
	if (val==GemdosOpcode::Ptrace) return "Ptrace";
	if (val==GemdosOpcode::Mvalidate) return "Mvalidate";
	if (val==GemdosOpcode::Dxreaddir) return "Dxreaddir";
	if (val==GemdosOpcode::Pseteuid) return "Pseteuid";
	if (val==GemdosOpcode::Psetegid) return "Psetegid";
	if (val==GemdosOpcode::Pgetauid) return "Pgetauid";
	if (val==GemdosOpcode::Psetauid) return "Psetauid";
	if (val==GemdosOpcode::Pgetgroups) return "Pgetgroups";
	if (val==GemdosOpcode::Psetgroups) return "Psetgroups";
	if (val==GemdosOpcode::Tsetitimer) return "Tsetitimer";
	if (val==GemdosOpcode::Scookie) return "Scookie";
	if (val==GemdosOpcode::Fstat64) return "Fstat64";
	if (val==GemdosOpcode::Fseek64) return "Fseek64";
	if (val==GemdosOpcode::Dsetkey) return "Dsetkey";
	if (val==GemdosOpcode::Psetreuid) return "Psetreuid";
	if (val==GemdosOpcode::Psetregid) return "Psetregid";
	if (val==GemdosOpcode::Ssync) return "Ssync";
	if (val==GemdosOpcode::Shutdown) return "Shutdown";
	if (val==GemdosOpcode::Dreadlabel) return "Dreadlabel";
	if (val==GemdosOpcode::Dwritelabel) return "Dwritelabel";
	if (val==GemdosOpcode::Ssystem) return "Ssystem";
	if (val==GemdosOpcode::Tgettimeofday) return "Tgettimeofday";
	if (val==GemdosOpcode::Tsettimeofday) return "Tsettimeofday";
	if (val==GemdosOpcode::Tadjtime) return "Tadjtime";
	if (val==GemdosOpcode::Pgetpriority) return "Pgetpriority";
	if (val==GemdosOpcode::Psetpriority) return "Psetpriority";
	if (val==GemdosOpcode::Fpoll) return "Fpoll";
	if (val==GemdosOpcode::Fwritev) return "Fwritev";
	if (val==GemdosOpcode::Freadv) return "Freadv";
	if (val==GemdosOpcode::Ffstat64) return "Ffstat64";
	if (val==GemdosOpcode::Psysctl) return "Psysctl";
	if (val==GemdosOpcode::Pemulation) return "Pemulation";
	if (val==GemdosOpcode::Fsocket) return "Fsocket";
	if (val==GemdosOpcode::Fsocketpair) return "Fsocketpair";
	if (val==GemdosOpcode::Faccept) return "Faccept";
	if (val==GemdosOpcode::Fconnect) return "Fconnect";
	if (val==GemdosOpcode::Fbind) return "Fbind";
	if (val==GemdosOpcode::Flisten) return "Flisten";
	if (val==GemdosOpcode::Frecvmsg) return "Frecvmsg";
	if (val==GemdosOpcode::Fsendmsg) return "Fsendmsg";
	if (val==GemdosOpcode::Frecvfrom) return "Frecvfrom";
	if (val==GemdosOpcode::Fsendto) return "Fsendto";
	if (val==GemdosOpcode::Fsetsockopt) return "Fsetsockopt";
	if (val==GemdosOpcode::Fgetsockopt) return "Fgetsockopt";
	if (val==GemdosOpcode::Fgetpeername) return "Fgetpeername";
	if (val==GemdosOpcode::Fgetsockname) return "Fgetsockname";
	if (val==GemdosOpcode::Fshutdown) return "Fshutdown";
	if (val==GemdosOpcode::Pshmget) return "Pshmget";
	if (val==GemdosOpcode::Pshmctl) return "Pshmctl";
	if (val==GemdosOpcode::Pshmat) return "Pshmat";
	if (val==GemdosOpcode::Pshmdt) return "Pshmdt";
	if (val==GemdosOpcode::Psemget) return "Psemget";
	if (val==GemdosOpcode::Psemctl) return "Psemctl";
	if (val==GemdosOpcode::Psemop) return "Psemop";
	if (val==GemdosOpcode::Psemconfig) return "Psemconfig";
	if (val==GemdosOpcode::Pmsgget) return "Pmsgget";
	if (val==GemdosOpcode::Pmsgctl) return "Pmsgctl";
	if (val==GemdosOpcode::Pmsgsnd) return "Pmsgsnd";
	if (val==GemdosOpcode::Pmsgrcv) return "Pmsgrcv";
	if (val==GemdosOpcode::Maccess) return "Maccess";
	if (val==GemdosOpcode::Fchown16) return "Fchown16";
	if (val==GemdosOpcode::Fchdir) return "Fchdir";
	if (val==GemdosOpcode::Ffdopendir) return "Ffdopendir";
	if (val==GemdosOpcode::Fdirfd) return "Fdirfd";
	return "?";
}
const stgen::StringDef g_enumDescs_GemdosOpcode[] = {
	{ 0, "" },
	{ 1, "" },
	{ 2, "" },
	{ 3, "" },
	{ 4, "" },
	{ 5, "" },
	{ 6, "" },
	{ 7, "" },
	{ 8, "" },
	{ 9, "" },
	{ 10, "" },
	{ 11, "" },
	{ 14, "" },
	{ 16, "" },
	{ 17, "" },
	{ 18, "" },
	{ 19, "" },
	{ 20, "" },
	{ 21, "(TOS 4)" },
	{ 22, "(MagiC)" },
	{ 23, "(MagiC)" },
	{ 25, "" },
	{ 26, "" },
	{ 32, "" },
	{ 42, "" },
	{ 43, "" },
	{ 44, "" },
	{ 45, "" },
	{ 47, "" },
	{ 48, "" },
	{ 49, "" },
	{ 51, "(MagiC)" },
	{ 54, "" },
	{ 57, "" },
	{ 58, "" },
	{ 59, "" },
	{ 60, "" },
	{ 61, "" },
	{ 62, "" },
	{ 63, "" },
	{ 64, "" },
	{ 65, "" },
	{ 66, "" },
	{ 67, "" },
	{ 68, "" },
	{ 69, "" },
	{ 70, "" },
	{ 71, "" },
	{ 72, "" },
	{ 73, "" },
	{ 74, "" },
	{ 75, "" },
	{ 76, "" },
	{ 78, "" },
	{ 79, "" },
	{ 86, "" },
	{ 87, "" },
	{ 92, "" },
	{ 96, "" },
	{ 98, "" },
	{ 99, "" },
	{ 100, "" },
	{ 101, "" },
	{ 102, "" },
	{ 255, "(MiNT)" },
	{ 256, "(MiNT)" },
	{ 257, "(MiNT)" },
	{ 258, "(MiNT)" },
	{ 259, "(MiNT)" },
	{ 260, "(MiNT)" },
	{ 261, "(MiNT)" },
	{ 262, "(MiNT)" },
	{ 263, "(MiNT)" },
	{ 264, "(MiNT)" },
	{ 265, "(MiNT)" },
	{ 266, "(MiNT)" },
	{ 267, "(MiNT)" },
	{ 268, "(MiNT)" },
	{ 269, "(MiNT)" },
	{ 270, "(MiNT)" },
	{ 271, "(MiNT)" },
	{ 272, "(MiNT)" },
	{ 273, "(MiNT)" },
	{ 274, "(MiNT)" },
	{ 275, "(MiNT)" },
	{ 276, "(MiNT)" },
	{ 277, "(MiNT)" },
	{ 278, "(MiNT)" },
	{ 279, "(MiNT)" },
	{ 280, "(MiNT)" },
	{ 281, "(MiNT)" },
	{ 282, "(MiNT)" },
	{ 283, "(MiNT)" },
	{ 284, "(MiNT)" },
	{ 285, "(MiNT)" },
	{ 286, "(MiNT)" },
	{ 287, "(MiNT)" },
	{ 288, "(MiNT)" },
	{ 289, "(MiNT)" },
	{ 290, "(MiNT)" },
	{ 291, "MiNT" },
	{ 292, "(MiNT)" },
	{ 293, "(MiNT)" },
	{ 294, "(MiNT)" },
	{ 295, "(MiNT)" },
	{ 296, "(MiNT)" },
	{ 297, "(MiNT)" },
	{ 298, "(MiNT)" },
	{ 299, "(MiNT)" },
	{ 300, "(MiNT)" },
	{ 301, "(MiNT)" },
	{ 302, "(MiNT)" },
	{ 303, "(MiNT)" },
	{ 304, "(MiNT)" },
	{ 305, "(MiNT)" },
	{ 306, "(MiNT)" },
	{ 307, "(MiNT)" },
	{ 308, "(MiNT)" },
	{ 309, "(MiNT)" },
	{ 310, "(MiNT)" },
	{ 311, "(MiNT)" },
	{ 312, "(MiNT)" },
	{ 313, "(MiNT)" },
	{ 314, "(MiNT)" },
	{ 315, "(MiNT)" },
	{ 316, "(MiNT)" },
	{ 317, "(MiNT 1.10)" },
	{ 318, "(MiNT 1.11 until FreeMiNT 1.15.12 inclusive)" },
	{ 319, "(MiNT 1.11)" },
	{ 320, "(MiNT)" },
	{ 321, "(MiNT)" },
	{ 322, "(MiNT 1.11)" },
	{ 323, "(MiNT 1.11)" },
	{ 324, "(MiNT 1.11)" },
	{ 325, "(MiNT 1.11)" },
	{ 326, "(MiNT 1.11)" },
	{ 327, "(MiNT 1.11)" },
	{ 328, "(MiNT 1.11)" },
	{ 329, "(MiNT 1.11)" },
	{ 330, "(MiNT (obsolete))" },
	{ 331, "(MiNT)" },
	{ 332, "(MiNT)" },
	{ 333, "(MiNT)" },
	{ 334, "(MiNT 1.12)" },
	{ 335, "(MiNT 1.12)" },
	{ 336, "(MiNT, MagiC)" },
	{ 337, "(MiNT)" },
	{ 338, "(MiNT 1.12)" },
	{ 339, "MiNT 1.12" },
	{ 340, "(MiNT 1.15.0)" },
	{ 341, "(MiNT 1.15.0)" },
	{ 342, "(MiNT 1.15.0)" },
	{ 343, "(MiNT)" },
	{ 344, "(MiNT 1.15.0)" },
	{ 345, "(MiNT 1.15.0)" },
	{ 346, "(MiNTNet)" },
	{ 347, "(MiNTNet)" },
	{ 348, "(MiNTNet)" },
	{ 349, "(MiNTNet)" },
	{ 350, "(MiNT)" },
	{ 351, "(MiNT)" },
	{ 352, "(MiNTNet)" },
	{ 353, "(MiNTNet)" },
	{ 354, "(MiNTNet)" },
	{ 355, "(MiNTNet)" },
	{ 356, "(MiNTNet)" },
	{ 357, "(MiNTNet)" },
	{ 358, "(MiNTNet)" },
	{ 359, "(MiNTNet)" },
	{ 360, "(MiNTNet)" },
	{ 361, "(MiNTNet)" },
	{ 362, "(MiNTNet)" },
	{ 363, "(MiNTNet)" },
	{ 364, "(MiNTNet)" },
	{ 365, "(MiNTNet)" },
	{ 366, "(MiNTNet)" },
	{ 368, "(MiNT)" },
	{ 369, "(MiNT)" },
	{ 370, "(MiNT)" },
	{ 371, "(MiNT)" },
	{ 372, "(MiNT)" },
	{ 373, "(MiNT)" },
	{ 374, "(MiNT)" },
	{ 375, "(MiNT)" },
	{ 376, "(MiNT)" },
	{ 377, "(MiNT)" },
	{ 378, "(MiNT)" },
	{ 379, "(MiNT)" },
	{ 381, "(MiNT)" },
	{ 384, "(FreeMiNT 1.16.0)" },
	{ 385, "(FreeMiNT 1.17)" },
	{ 386, "(FreeMiNT 1.17)" },
	{ 387, "(FreeMiNT 1.17)" },
	{ 0, nullptr }
};
/* Register Field Sets */

} // namespace
