/* Autogenerated file */


#ifndef STGEN_gemdos_H
#define STGEN_gemdos_H
#include <stdint.h>

#include "stgen.h"

namespace Gemdos {


/* Enum GemdosOpcode */
enum class GemdosOpcode : uint32_t {
	Pterm0               =      0, /*  */
	Cconin               =      1, /*  */
	Cconout              =      2, /*  */
	Cauxin               =      3, /*  */
	Cauxout              =      4, /*  */
	Cprnout              =      5, /*  */
	Crawio               =      6, /*  */
	Crawcin              =      7, /*  */
	Cnecin               =      8, /*  */
	Cconws               =      9, /*  */
	Cconrs               =     10, /*  */
	Cconis               =     11, /*  */
	Dsetdrv              =     14, /*  */
	Cconos               =     16, /*  */
	Cprnos               =     17, /*  */
	Cauxis               =     18, /*  */
	Cauxos               =     19, /*  */
	Maddalt              =     20, /*  */
	Srealloc             =     21, /* (TOS 4) */
	Slbopen              =     22, /* (MagiC) */
	Slbclose             =     23, /* (MagiC) */
	Dgetdrv              =     25, /*  */
	Fsetdta              =     26, /*  */
	Super                =     32, /*  */
	Tgetdate             =     42, /*  */
	Tsetdate             =     43, /*  */
	Tgettime             =     44, /*  */
	Tsettime             =     45, /*  */
	Fgetdta              =     47, /*  */
	Sversion             =     48, /*  */
	Ptermres             =     49, /*  */
	Sconfig              =     51, /* (MagiC) */
	Dfree                =     54, /*  */
	Dcreate              =     57, /*  */
	Ddelete              =     58, /*  */
	Dsetpath             =     59, /*  */
	Fcreate              =     60, /*  */
	Fopen                =     61, /*  */
	Fclose               =     62, /*  */
	Fread                =     63, /*  */
	Fwrite               =     64, /*  */
	Fdelete              =     65, /*  */
	Fseek                =     66, /*  */
	Fattrib              =     67, /*  */
	Mxalloc              =     68, /*  */
	Fdup                 =     69, /*  */
	Fforce               =     70, /*  */
	Dgetpath             =     71, /*  */
	Malloc               =     72, /*  */
	Mfree                =     73, /*  */
	Mshrink              =     74, /*  */
	Pexec                =     75, /*  */
	Pterm                =     76, /*  */
	Fsfirst              =     78, /*  */
	Fsnext               =     79, /*  */
	Frename              =     86, /*  */
	Fdatime              =     87, /*  */
	Flock                =     92, /*  */
	Nversion             =     96, /*  */
	Frlock               =     98, /*  */
	Frunlock             =     99, /*  */
	F_lock               =    100, /*  */
	Funlock              =    101, /*  */
	Fflush               =    102, /*  */
	Syield               =    255, /* (MiNT) */
	Fpipe                =    256, /* (MiNT) */
	Ffchown              =    257, /* (MiNT) */
	Ffchmod              =    258, /* (MiNT) */
	Fsync                =    259, /* (MiNT) */
	Fcntl                =    260, /* (MiNT) */
	Finstat              =    261, /* (MiNT) */
	Foutstat             =    262, /* (MiNT) */
	Fgetchar             =    263, /* (MiNT) */
	Fputchar             =    264, /* (MiNT) */
	Pwait                =    265, /* (MiNT) */
	Pnice                =    266, /* (MiNT) */
	Pgetpid              =    267, /* (MiNT) */
	Pgetppid             =    268, /* (MiNT) */
	Pgetpgrp             =    269, /* (MiNT) */
	Psetpgrp             =    270, /* (MiNT) */
	Pgetuid              =    271, /* (MiNT) */
	Psetuid              =    272, /* (MiNT) */
	Pkill                =    273, /* (MiNT) */
	Psignal              =    274, /* (MiNT) */
	Pvfork               =    275, /* (MiNT) */
	Pgetgid              =    276, /* (MiNT) */
	Psetgid              =    277, /* (MiNT) */
	Psigblock            =    278, /* (MiNT) */
	Psigsetmask          =    279, /* (MiNT) */
	Pusrval              =    280, /* (MiNT) */
	Pdomain              =    281, /* (MiNT) */
	Psigreturn           =    282, /* (MiNT) */
	Pfork                =    283, /* (MiNT) */
	Pwait3               =    284, /* (MiNT) */
	Fselect              =    285, /* (MiNT) */
	Prusage              =    286, /* (MiNT) */
	Psetlimit            =    287, /* (MiNT) */
	Talarm               =    288, /* (MiNT) */
	Pause                =    289, /* (MiNT) */
	Sysconf              =    290, /* (MiNT) */
	Psigpending          =    291, /* MiNT */
	Dpathconf            =    292, /* (MiNT) */
	Pmsg                 =    293, /* (MiNT) */
	Fmidipipe            =    294, /* (MiNT) */
	Prenice              =    295, /* (MiNT) */
	Dopendir             =    296, /* (MiNT) */
	Dreaddir             =    297, /* (MiNT) */
	Drewinddir           =    298, /* (MiNT) */
	Dclosedir            =    299, /* (MiNT) */
	Fxattr               =    300, /* (MiNT) */
	Flink                =    301, /* (MiNT) */
	Fsymlink             =    302, /* (MiNT) */
	Freadlink            =    303, /* (MiNT) */
	Dcntl                =    304, /* (MiNT) */
	Fchown               =    305, /* (MiNT) */
	Fchmod               =    306, /* (MiNT) */
	Pumask               =    307, /* (MiNT) */
	Psemaphore           =    308, /* (MiNT) */
	Dlock                =    309, /* (MiNT) */
	Psigpause            =    310, /* (MiNT) */
	Psigaction           =    311, /* (MiNT) */
	Pgeteuid             =    312, /* (MiNT) */
	Pgetegid             =    313, /* (MiNT) */
	Pwaitpid             =    314, /* (MiNT) */
	Dgetcwd              =    315, /* (MiNT) */
	Salert               =    316, /* (MiNT) */
	Tmalarm              =    317, /* (MiNT 1.10) */
	Psigintr             =    318, /* (MiNT 1.11 until FreeMiNT 1.15.12 inclusive) */
	Suptime              =    319, /* (MiNT 1.11) */
	Ptrace               =    320, /* (MiNT) */
	Mvalidate            =    321, /* (MiNT) */
	Dxreaddir            =    322, /* (MiNT 1.11) */
	Pseteuid             =    323, /* (MiNT 1.11) */
	Psetegid             =    324, /* (MiNT 1.11) */
	Pgetauid             =    325, /* (MiNT 1.11) */
	Psetauid             =    326, /* (MiNT 1.11) */
	Pgetgroups           =    327, /* (MiNT 1.11) */
	Psetgroups           =    328, /* (MiNT 1.11) */
	Tsetitimer           =    329, /* (MiNT 1.11) */
	Scookie              =    330, /* (MiNT (obsolete)) */
	Fstat64              =    331, /* (MiNT) */
	Fseek64              =    332, /* (MiNT) */
	Dsetkey              =    333, /* (MiNT) */
	Psetreuid            =    334, /* (MiNT 1.12) */
	Psetregid            =    335, /* (MiNT 1.12) */
	Ssync                =    336, /* (MiNT, MagiC) */
	Shutdown             =    337, /* (MiNT) */
	Dreadlabel           =    338, /* (MiNT 1.12) */
	Dwritelabel          =    339, /* MiNT 1.12 */
	Ssystem              =    340, /* (MiNT 1.15.0) */
	Tgettimeofday        =    341, /* (MiNT 1.15.0) */
	Tsettimeofday        =    342, /* (MiNT 1.15.0) */
	Tadjtime             =    343, /* (MiNT) */
	Pgetpriority         =    344, /* (MiNT 1.15.0) */
	Psetpriority         =    345, /* (MiNT 1.15.0) */
	Fpoll                =    346, /* (MiNTNet) */
	Fwritev              =    347, /* (MiNTNet) */
	Freadv               =    348, /* (MiNTNet) */
	Ffstat64             =    349, /* (MiNTNet) */
	Psysctl              =    350, /* (MiNT) */
	Pemulation           =    351, /* (MiNT) */
	Fsocket              =    352, /* (MiNTNet) */
	Fsocketpair          =    353, /* (MiNTNet) */
	Faccept              =    354, /* (MiNTNet) */
	Fconnect             =    355, /* (MiNTNet) */
	Fbind                =    356, /* (MiNTNet) */
	Flisten              =    357, /* (MiNTNet) */
	Frecvmsg             =    358, /* (MiNTNet) */
	Fsendmsg             =    359, /* (MiNTNet) */
	Frecvfrom            =    360, /* (MiNTNet) */
	Fsendto              =    361, /* (MiNTNet) */
	Fsetsockopt          =    362, /* (MiNTNet) */
	Fgetsockopt          =    363, /* (MiNTNet) */
	Fgetpeername         =    364, /* (MiNTNet) */
	Fgetsockname         =    365, /* (MiNTNet) */
	Fshutdown            =    366, /* (MiNTNet) */
	Pshmget              =    368, /* (MiNT) */
	Pshmctl              =    369, /* (MiNT) */
	Pshmat               =    370, /* (MiNT) */
	Pshmdt               =    371, /* (MiNT) */
	Psemget              =    372, /* (MiNT) */
	Psemctl              =    373, /* (MiNT) */
	Psemop               =    374, /* (MiNT) */
	Psemconfig           =    375, /* (MiNT) */
	Pmsgget              =    376, /* (MiNT) */
	Pmsgctl              =    377, /* (MiNT) */
	Pmsgsnd              =    378, /* (MiNT) */
	Pmsgrcv              =    379, /* (MiNT) */
	Maccess              =    381, /* (MiNT) */
	Fchown16             =    384, /* (FreeMiNT 1.16.0) */
	Fchdir               =    385, /* (FreeMiNT 1.17) */
	Ffdopendir           =    386, /* (FreeMiNT 1.17) */
	Fdirfd               =    387  /* (FreeMiNT 1.17) */
};

/* Enum -> string lookup declarations */
extern const char* GetString(GemdosOpcode val);
extern const char* GetEnumString(GemdosOpcode val);

/* Register Addresses */

/* Register Field Accessors */

/* Register Field Sets */

} // namespace
#endif
