/* Autogenerated file */

#include "gemdos.h"

namespace Gemdos {

const char* GetString(Opcode val)
{
	if (val==Opcode::Pterm0) return "Terminate proceess";
	if (val==Opcode::Cconin) return "Read char from Standard Input";
	if (val==Opcode::Cconout) return "Write char to Standard Output";
	if (val==Opcode::Cauxin) return "Read char from AUX";
	if (val==Opcode::Cauxout) return "Write char to AUX";
	if (val==Opcode::Cprnout) return "Write char to standard PRN";
	if (val==Opcode::Crawio) return "Raw I/O to Standard Input/Output";
	if (val==Opcode::Crawcin) return "Raw Input from Standard Input";
	if (val==Opcode::Cnecin) return "Read char from Standard Input, no echo";
	if (val==Opcode::Cconws) return "Write string to Standard Output";
	if (val==Opcode::Cconrs) return "Read edited string from Standard Input";
	if (val==Opcode::Cconis) return "Check status of Standard Input";
	if (val==Opcode::Dsetdrv) return "Set default drive";
	if (val==Opcode::Cconos) return "Check status of Standard Output";
	if (val==Opcode::Cprnos) return "Check status of standard PRN";
	if (val==Opcode::Cauxis) return "Check input status of AUX";
	if (val==Opcode::Cauxos) return "Check output status of AUX";
	if (val==Opcode::Maddalt) return "";
	if (val==Opcode::Srealloc) return "(TOS 4)";
	if (val==Opcode::Slbopen) return "(MagiC)";
	if (val==Opcode::Slbclose) return "(MagiC)";
	if (val==Opcode::Dgetdrv) return "Get default drive";
	if (val==Opcode::Fsetdta) return "Set Disk Transfer Address";
	if (val==Opcode::Super) return "Get/set/inquire Supervisor Mode";
	if (val==Opcode::Tgetdate) return "Get date";
	if (val==Opcode::Tsetdate) return "Set date";
	if (val==Opcode::Tgettime) return "Get time";
	if (val==Opcode::Tsettime) return "Set time";
	if (val==Opcode::Fgetdta) return "Get Disk Transfer Address";
	if (val==Opcode::Sversion) return "Get Version Number";
	if (val==Opcode::Ptermres) return "Terminate and stay resident";
	if (val==Opcode::Sconfig) return "(MagiC)";
	if (val==Opcode::Dfree) return "Get drive free space";
	if (val==Opcode::Dcreate) return "Create directory";
	if (val==Opcode::Ddelete) return "Delete directory";
	if (val==Opcode::Dsetpath) return "Set current directory";
	if (val==Opcode::Fcreate) return "Create file";
	if (val==Opcode::Fopen) return "Open file";
	if (val==Opcode::Fclose) return "Close file";
	if (val==Opcode::Fread) return "Read file";
	if (val==Opcode::Fwrite) return "Write to file";
	if (val==Opcode::Fdelete) return "Delete file";
	if (val==Opcode::Fseek) return "Seek file pointer";
	if (val==Opcode::Fattrib) return "Get/set file attributes";
	if (val==Opcode::Mxalloc) return "Extended allocate memory";
	if (val==Opcode::Fdup) return "Duplicate file handle";
	if (val==Opcode::Fforce) return "Force file handle";
	if (val==Opcode::Dgetpath) return "Get current directory";
	if (val==Opcode::Malloc) return "Allocate memory";
	if (val==Opcode::Mfree) return "Release memory";
	if (val==Opcode::Mshrink) return "Shrink allocated block";
	if (val==Opcode::Pexec) return "Load/execute process";
	if (val==Opcode::Pterm) return "Terminate process";
	if (val==Opcode::Fsfirst) return "Search first";
	if (val==Opcode::Fsnext) return "Search next";
	if (val==Opcode::Frename) return "Rename file";
	if (val==Opcode::Fdatime) return "Get/set file timestamp";
	if (val==Opcode::Flock) return "";
	if (val==Opcode::Nversion) return "";
	if (val==Opcode::Frlock) return "";
	if (val==Opcode::Frunlock) return "";
	if (val==Opcode::F_lock) return "";
	if (val==Opcode::Funlock) return "";
	if (val==Opcode::Fflush) return "";
	if (val==Opcode::Syield) return "(MiNT)";
	if (val==Opcode::Fpipe) return "(MiNT)";
	if (val==Opcode::Ffchown) return "(MiNT)";
	if (val==Opcode::Ffchmod) return "(MiNT)";
	if (val==Opcode::Fsync) return "(MiNT)";
	if (val==Opcode::Fcntl) return "(MiNT)";
	if (val==Opcode::Finstat) return "(MiNT)";
	if (val==Opcode::Foutstat) return "(MiNT)";
	if (val==Opcode::Fgetchar) return "(MiNT)";
	if (val==Opcode::Fputchar) return "(MiNT)";
	if (val==Opcode::Pwait) return "(MiNT)";
	if (val==Opcode::Pnice) return "(MiNT)";
	if (val==Opcode::Pgetpid) return "(MiNT)";
	if (val==Opcode::Pgetppid) return "(MiNT)";
	if (val==Opcode::Pgetpgrp) return "(MiNT)";
	if (val==Opcode::Psetpgrp) return "(MiNT)";
	if (val==Opcode::Pgetuid) return "(MiNT)";
	if (val==Opcode::Psetuid) return "(MiNT)";
	if (val==Opcode::Pkill) return "(MiNT)";
	if (val==Opcode::Psignal) return "(MiNT)";
	if (val==Opcode::Pvfork) return "(MiNT)";
	if (val==Opcode::Pgetgid) return "(MiNT)";
	if (val==Opcode::Psetgid) return "(MiNT)";
	if (val==Opcode::Psigblock) return "(MiNT)";
	if (val==Opcode::Psigsetmask) return "(MiNT)";
	if (val==Opcode::Pusrval) return "(MiNT)";
	if (val==Opcode::Pdomain) return "(MiNT)";
	if (val==Opcode::Psigreturn) return "(MiNT)";
	if (val==Opcode::Pfork) return "(MiNT)";
	if (val==Opcode::Pwait3) return "(MiNT)";
	if (val==Opcode::Fselect) return "(MiNT)";
	if (val==Opcode::Prusage) return "(MiNT)";
	if (val==Opcode::Psetlimit) return "(MiNT)";
	if (val==Opcode::Talarm) return "(MiNT)";
	if (val==Opcode::Pause) return "(MiNT)";
	if (val==Opcode::Sysconf) return "(MiNT)";
	if (val==Opcode::Psigpending) return "MiNT";
	if (val==Opcode::Dpathconf) return "(MiNT)";
	if (val==Opcode::Pmsg) return "(MiNT)";
	if (val==Opcode::Fmidipipe) return "(MiNT)";
	if (val==Opcode::Prenice) return "(MiNT)";
	if (val==Opcode::Dopendir) return "(MiNT)";
	if (val==Opcode::Dreaddir) return "(MiNT)";
	if (val==Opcode::Drewinddir) return "(MiNT)";
	if (val==Opcode::Dclosedir) return "(MiNT)";
	if (val==Opcode::Fxattr) return "(MiNT)";
	if (val==Opcode::Flink) return "(MiNT)";
	if (val==Opcode::Fsymlink) return "(MiNT)";
	if (val==Opcode::Freadlink) return "(MiNT)";
	if (val==Opcode::Dcntl) return "(MiNT)";
	if (val==Opcode::Fchown) return "(MiNT)";
	if (val==Opcode::Fchmod) return "(MiNT)";
	if (val==Opcode::Pumask) return "(MiNT)";
	if (val==Opcode::Psemaphore) return "(MiNT)";
	if (val==Opcode::Dlock) return "(MiNT)";
	if (val==Opcode::Psigpause) return "(MiNT)";
	if (val==Opcode::Psigaction) return "(MiNT)";
	if (val==Opcode::Pgeteuid) return "(MiNT)";
	if (val==Opcode::Pgetegid) return "(MiNT)";
	if (val==Opcode::Pwaitpid) return "(MiNT)";
	if (val==Opcode::Dgetcwd) return "(MiNT)";
	if (val==Opcode::Salert) return "(MiNT)";
	if (val==Opcode::Tmalarm) return "(MiNT 1.10)";
	if (val==Opcode::Psigintr) return "(MiNT 1.11 until FreeMiNT 1.15.12 inclusive)";
	if (val==Opcode::Suptime) return "(MiNT 1.11)";
	if (val==Opcode::Ptrace) return "(MiNT)";
	if (val==Opcode::Mvalidate) return "(MiNT)";
	if (val==Opcode::Dxreaddir) return "(MiNT 1.11)";
	if (val==Opcode::Pseteuid) return "(MiNT 1.11)";
	if (val==Opcode::Psetegid) return "(MiNT 1.11)";
	if (val==Opcode::Pgetauid) return "(MiNT 1.11)";
	if (val==Opcode::Psetauid) return "(MiNT 1.11)";
	if (val==Opcode::Pgetgroups) return "(MiNT 1.11)";
	if (val==Opcode::Psetgroups) return "(MiNT 1.11)";
	if (val==Opcode::Tsetitimer) return "(MiNT 1.11)";
	if (val==Opcode::Scookie) return "(MiNT (obsolete))";
	if (val==Opcode::Fstat64) return "(MiNT)";
	if (val==Opcode::Fseek64) return "(MiNT)";
	if (val==Opcode::Dsetkey) return "(MiNT)";
	if (val==Opcode::Psetreuid) return "(MiNT 1.12)";
	if (val==Opcode::Psetregid) return "(MiNT 1.12)";
	if (val==Opcode::Ssync) return "(MiNT, MagiC)";
	if (val==Opcode::Shutdown) return "(MiNT)";
	if (val==Opcode::Dreadlabel) return "(MiNT 1.12)";
	if (val==Opcode::Dwritelabel) return "MiNT 1.12";
	if (val==Opcode::Ssystem) return "(MiNT 1.15.0)";
	if (val==Opcode::Tgettimeofday) return "(MiNT 1.15.0)";
	if (val==Opcode::Tsettimeofday) return "(MiNT 1.15.0)";
	if (val==Opcode::Tadjtime) return "(MiNT)";
	if (val==Opcode::Pgetpriority) return "(MiNT 1.15.0)";
	if (val==Opcode::Psetpriority) return "(MiNT 1.15.0)";
	if (val==Opcode::Fpoll) return "(MiNTNet)";
	if (val==Opcode::Fwritev) return "(MiNTNet)";
	if (val==Opcode::Freadv) return "(MiNTNet)";
	if (val==Opcode::Ffstat64) return "(MiNTNet)";
	if (val==Opcode::Psysctl) return "(MiNT)";
	if (val==Opcode::Pemulation) return "(MiNT)";
	if (val==Opcode::Fsocket) return "(MiNTNet)";
	if (val==Opcode::Fsocketpair) return "(MiNTNet)";
	if (val==Opcode::Faccept) return "(MiNTNet)";
	if (val==Opcode::Fconnect) return "(MiNTNet)";
	if (val==Opcode::Fbind) return "(MiNTNet)";
	if (val==Opcode::Flisten) return "(MiNTNet)";
	if (val==Opcode::Frecvmsg) return "(MiNTNet)";
	if (val==Opcode::Fsendmsg) return "(MiNTNet)";
	if (val==Opcode::Frecvfrom) return "(MiNTNet)";
	if (val==Opcode::Fsendto) return "(MiNTNet)";
	if (val==Opcode::Fsetsockopt) return "(MiNTNet)";
	if (val==Opcode::Fgetsockopt) return "(MiNTNet)";
	if (val==Opcode::Fgetpeername) return "(MiNTNet)";
	if (val==Opcode::Fgetsockname) return "(MiNTNet)";
	if (val==Opcode::Fshutdown) return "(MiNTNet)";
	if (val==Opcode::Pshmget) return "(MiNT)";
	if (val==Opcode::Pshmctl) return "(MiNT)";
	if (val==Opcode::Pshmat) return "(MiNT)";
	if (val==Opcode::Pshmdt) return "(MiNT)";
	if (val==Opcode::Psemget) return "(MiNT)";
	if (val==Opcode::Psemctl) return "(MiNT)";
	if (val==Opcode::Psemop) return "(MiNT)";
	if (val==Opcode::Psemconfig) return "(MiNT)";
	if (val==Opcode::Pmsgget) return "(MiNT)";
	if (val==Opcode::Pmsgctl) return "(MiNT)";
	if (val==Opcode::Pmsgsnd) return "(MiNT)";
	if (val==Opcode::Pmsgrcv) return "(MiNT)";
	if (val==Opcode::Maccess) return "(MiNT)";
	if (val==Opcode::Fchown16) return "(FreeMiNT 1.16.0)";
	if (val==Opcode::Fchdir) return "(FreeMiNT 1.17)";
	if (val==Opcode::Ffdopendir) return "(FreeMiNT 1.17)";
	if (val==Opcode::Fdirfd) return "(FreeMiNT 1.17)";
	return "?";
}
const char* GetEnumString(Opcode val)
{
	if (val==Opcode::Pterm0) return "Pterm0";
	if (val==Opcode::Cconin) return "Cconin";
	if (val==Opcode::Cconout) return "Cconout";
	if (val==Opcode::Cauxin) return "Cauxin";
	if (val==Opcode::Cauxout) return "Cauxout";
	if (val==Opcode::Cprnout) return "Cprnout";
	if (val==Opcode::Crawio) return "Crawio";
	if (val==Opcode::Crawcin) return "Crawcin";
	if (val==Opcode::Cnecin) return "Cnecin";
	if (val==Opcode::Cconws) return "Cconws";
	if (val==Opcode::Cconrs) return "Cconrs";
	if (val==Opcode::Cconis) return "Cconis";
	if (val==Opcode::Dsetdrv) return "Dsetdrv";
	if (val==Opcode::Cconos) return "Cconos";
	if (val==Opcode::Cprnos) return "Cprnos";
	if (val==Opcode::Cauxis) return "Cauxis";
	if (val==Opcode::Cauxos) return "Cauxos";
	if (val==Opcode::Maddalt) return "Maddalt";
	if (val==Opcode::Srealloc) return "Srealloc";
	if (val==Opcode::Slbopen) return "Slbopen";
	if (val==Opcode::Slbclose) return "Slbclose";
	if (val==Opcode::Dgetdrv) return "Dgetdrv";
	if (val==Opcode::Fsetdta) return "Fsetdta";
	if (val==Opcode::Super) return "Super";
	if (val==Opcode::Tgetdate) return "Tgetdate";
	if (val==Opcode::Tsetdate) return "Tsetdate";
	if (val==Opcode::Tgettime) return "Tgettime";
	if (val==Opcode::Tsettime) return "Tsettime";
	if (val==Opcode::Fgetdta) return "Fgetdta";
	if (val==Opcode::Sversion) return "Sversion";
	if (val==Opcode::Ptermres) return "Ptermres";
	if (val==Opcode::Sconfig) return "Sconfig";
	if (val==Opcode::Dfree) return "Dfree";
	if (val==Opcode::Dcreate) return "Dcreate";
	if (val==Opcode::Ddelete) return "Ddelete";
	if (val==Opcode::Dsetpath) return "Dsetpath";
	if (val==Opcode::Fcreate) return "Fcreate";
	if (val==Opcode::Fopen) return "Fopen";
	if (val==Opcode::Fclose) return "Fclose";
	if (val==Opcode::Fread) return "Fread";
	if (val==Opcode::Fwrite) return "Fwrite";
	if (val==Opcode::Fdelete) return "Fdelete";
	if (val==Opcode::Fseek) return "Fseek";
	if (val==Opcode::Fattrib) return "Fattrib";
	if (val==Opcode::Mxalloc) return "Mxalloc";
	if (val==Opcode::Fdup) return "Fdup";
	if (val==Opcode::Fforce) return "Fforce";
	if (val==Opcode::Dgetpath) return "Dgetpath";
	if (val==Opcode::Malloc) return "Malloc";
	if (val==Opcode::Mfree) return "Mfree";
	if (val==Opcode::Mshrink) return "Mshrink";
	if (val==Opcode::Pexec) return "Pexec";
	if (val==Opcode::Pterm) return "Pterm";
	if (val==Opcode::Fsfirst) return "Fsfirst";
	if (val==Opcode::Fsnext) return "Fsnext";
	if (val==Opcode::Frename) return "Frename";
	if (val==Opcode::Fdatime) return "Fdatime";
	if (val==Opcode::Flock) return "Flock";
	if (val==Opcode::Nversion) return "Nversion";
	if (val==Opcode::Frlock) return "Frlock";
	if (val==Opcode::Frunlock) return "Frunlock";
	if (val==Opcode::F_lock) return "F_lock";
	if (val==Opcode::Funlock) return "Funlock";
	if (val==Opcode::Fflush) return "Fflush";
	if (val==Opcode::Syield) return "Syield";
	if (val==Opcode::Fpipe) return "Fpipe";
	if (val==Opcode::Ffchown) return "Ffchown";
	if (val==Opcode::Ffchmod) return "Ffchmod";
	if (val==Opcode::Fsync) return "Fsync";
	if (val==Opcode::Fcntl) return "Fcntl";
	if (val==Opcode::Finstat) return "Finstat";
	if (val==Opcode::Foutstat) return "Foutstat";
	if (val==Opcode::Fgetchar) return "Fgetchar";
	if (val==Opcode::Fputchar) return "Fputchar";
	if (val==Opcode::Pwait) return "Pwait";
	if (val==Opcode::Pnice) return "Pnice";
	if (val==Opcode::Pgetpid) return "Pgetpid";
	if (val==Opcode::Pgetppid) return "Pgetppid";
	if (val==Opcode::Pgetpgrp) return "Pgetpgrp";
	if (val==Opcode::Psetpgrp) return "Psetpgrp";
	if (val==Opcode::Pgetuid) return "Pgetuid";
	if (val==Opcode::Psetuid) return "Psetuid";
	if (val==Opcode::Pkill) return "Pkill";
	if (val==Opcode::Psignal) return "Psignal";
	if (val==Opcode::Pvfork) return "Pvfork";
	if (val==Opcode::Pgetgid) return "Pgetgid";
	if (val==Opcode::Psetgid) return "Psetgid";
	if (val==Opcode::Psigblock) return "Psigblock";
	if (val==Opcode::Psigsetmask) return "Psigsetmask";
	if (val==Opcode::Pusrval) return "Pusrval";
	if (val==Opcode::Pdomain) return "Pdomain";
	if (val==Opcode::Psigreturn) return "Psigreturn";
	if (val==Opcode::Pfork) return "Pfork";
	if (val==Opcode::Pwait3) return "Pwait3";
	if (val==Opcode::Fselect) return "Fselect";
	if (val==Opcode::Prusage) return "Prusage";
	if (val==Opcode::Psetlimit) return "Psetlimit";
	if (val==Opcode::Talarm) return "Talarm";
	if (val==Opcode::Pause) return "Pause";
	if (val==Opcode::Sysconf) return "Sysconf";
	if (val==Opcode::Psigpending) return "Psigpending";
	if (val==Opcode::Dpathconf) return "Dpathconf";
	if (val==Opcode::Pmsg) return "Pmsg";
	if (val==Opcode::Fmidipipe) return "Fmidipipe";
	if (val==Opcode::Prenice) return "Prenice";
	if (val==Opcode::Dopendir) return "Dopendir";
	if (val==Opcode::Dreaddir) return "Dreaddir";
	if (val==Opcode::Drewinddir) return "Drewinddir";
	if (val==Opcode::Dclosedir) return "Dclosedir";
	if (val==Opcode::Fxattr) return "Fxattr";
	if (val==Opcode::Flink) return "Flink";
	if (val==Opcode::Fsymlink) return "Fsymlink";
	if (val==Opcode::Freadlink) return "Freadlink";
	if (val==Opcode::Dcntl) return "Dcntl";
	if (val==Opcode::Fchown) return "Fchown";
	if (val==Opcode::Fchmod) return "Fchmod";
	if (val==Opcode::Pumask) return "Pumask";
	if (val==Opcode::Psemaphore) return "Psemaphore";
	if (val==Opcode::Dlock) return "Dlock";
	if (val==Opcode::Psigpause) return "Psigpause";
	if (val==Opcode::Psigaction) return "Psigaction";
	if (val==Opcode::Pgeteuid) return "Pgeteuid";
	if (val==Opcode::Pgetegid) return "Pgetegid";
	if (val==Opcode::Pwaitpid) return "Pwaitpid";
	if (val==Opcode::Dgetcwd) return "Dgetcwd";
	if (val==Opcode::Salert) return "Salert";
	if (val==Opcode::Tmalarm) return "Tmalarm";
	if (val==Opcode::Psigintr) return "Psigintr";
	if (val==Opcode::Suptime) return "Suptime";
	if (val==Opcode::Ptrace) return "Ptrace";
	if (val==Opcode::Mvalidate) return "Mvalidate";
	if (val==Opcode::Dxreaddir) return "Dxreaddir";
	if (val==Opcode::Pseteuid) return "Pseteuid";
	if (val==Opcode::Psetegid) return "Psetegid";
	if (val==Opcode::Pgetauid) return "Pgetauid";
	if (val==Opcode::Psetauid) return "Psetauid";
	if (val==Opcode::Pgetgroups) return "Pgetgroups";
	if (val==Opcode::Psetgroups) return "Psetgroups";
	if (val==Opcode::Tsetitimer) return "Tsetitimer";
	if (val==Opcode::Scookie) return "Scookie";
	if (val==Opcode::Fstat64) return "Fstat64";
	if (val==Opcode::Fseek64) return "Fseek64";
	if (val==Opcode::Dsetkey) return "Dsetkey";
	if (val==Opcode::Psetreuid) return "Psetreuid";
	if (val==Opcode::Psetregid) return "Psetregid";
	if (val==Opcode::Ssync) return "Ssync";
	if (val==Opcode::Shutdown) return "Shutdown";
	if (val==Opcode::Dreadlabel) return "Dreadlabel";
	if (val==Opcode::Dwritelabel) return "Dwritelabel";
	if (val==Opcode::Ssystem) return "Ssystem";
	if (val==Opcode::Tgettimeofday) return "Tgettimeofday";
	if (val==Opcode::Tsettimeofday) return "Tsettimeofday";
	if (val==Opcode::Tadjtime) return "Tadjtime";
	if (val==Opcode::Pgetpriority) return "Pgetpriority";
	if (val==Opcode::Psetpriority) return "Psetpriority";
	if (val==Opcode::Fpoll) return "Fpoll";
	if (val==Opcode::Fwritev) return "Fwritev";
	if (val==Opcode::Freadv) return "Freadv";
	if (val==Opcode::Ffstat64) return "Ffstat64";
	if (val==Opcode::Psysctl) return "Psysctl";
	if (val==Opcode::Pemulation) return "Pemulation";
	if (val==Opcode::Fsocket) return "Fsocket";
	if (val==Opcode::Fsocketpair) return "Fsocketpair";
	if (val==Opcode::Faccept) return "Faccept";
	if (val==Opcode::Fconnect) return "Fconnect";
	if (val==Opcode::Fbind) return "Fbind";
	if (val==Opcode::Flisten) return "Flisten";
	if (val==Opcode::Frecvmsg) return "Frecvmsg";
	if (val==Opcode::Fsendmsg) return "Fsendmsg";
	if (val==Opcode::Frecvfrom) return "Frecvfrom";
	if (val==Opcode::Fsendto) return "Fsendto";
	if (val==Opcode::Fsetsockopt) return "Fsetsockopt";
	if (val==Opcode::Fgetsockopt) return "Fgetsockopt";
	if (val==Opcode::Fgetpeername) return "Fgetpeername";
	if (val==Opcode::Fgetsockname) return "Fgetsockname";
	if (val==Opcode::Fshutdown) return "Fshutdown";
	if (val==Opcode::Pshmget) return "Pshmget";
	if (val==Opcode::Pshmctl) return "Pshmctl";
	if (val==Opcode::Pshmat) return "Pshmat";
	if (val==Opcode::Pshmdt) return "Pshmdt";
	if (val==Opcode::Psemget) return "Psemget";
	if (val==Opcode::Psemctl) return "Psemctl";
	if (val==Opcode::Psemop) return "Psemop";
	if (val==Opcode::Psemconfig) return "Psemconfig";
	if (val==Opcode::Pmsgget) return "Pmsgget";
	if (val==Opcode::Pmsgctl) return "Pmsgctl";
	if (val==Opcode::Pmsgsnd) return "Pmsgsnd";
	if (val==Opcode::Pmsgrcv) return "Pmsgrcv";
	if (val==Opcode::Maccess) return "Maccess";
	if (val==Opcode::Fchown16) return "Fchown16";
	if (val==Opcode::Fchdir) return "Fchdir";
	if (val==Opcode::Ffdopendir) return "Ffdopendir";
	if (val==Opcode::Fdirfd) return "Fdirfd";
	return "?";
}
const stgen::StringDef g_enumDescs_Opcode[] = {
	{ 0, "Terminate proceess" },
	{ 1, "Read char from Standard Input" },
	{ 2, "Write char to Standard Output" },
	{ 3, "Read char from AUX" },
	{ 4, "Write char to AUX" },
	{ 5, "Write char to standard PRN" },
	{ 6, "Raw I/O to Standard Input/Output" },
	{ 7, "Raw Input from Standard Input" },
	{ 8, "Read char from Standard Input, no echo" },
	{ 9, "Write string to Standard Output" },
	{ 10, "Read edited string from Standard Input" },
	{ 11, "Check status of Standard Input" },
	{ 14, "Set default drive" },
	{ 16, "Check status of Standard Output" },
	{ 17, "Check status of standard PRN" },
	{ 18, "Check input status of AUX" },
	{ 19, "Check output status of AUX" },
	{ 20, "" },
	{ 21, "(TOS 4)" },
	{ 22, "(MagiC)" },
	{ 23, "(MagiC)" },
	{ 25, "Get default drive" },
	{ 26, "Set Disk Transfer Address" },
	{ 32, "Get/set/inquire Supervisor Mode" },
	{ 42, "Get date" },
	{ 43, "Set date" },
	{ 44, "Get time" },
	{ 45, "Set time" },
	{ 47, "Get Disk Transfer Address" },
	{ 48, "Get Version Number" },
	{ 49, "Terminate and stay resident" },
	{ 51, "(MagiC)" },
	{ 54, "Get drive free space" },
	{ 57, "Create directory" },
	{ 58, "Delete directory" },
	{ 59, "Set current directory" },
	{ 60, "Create file" },
	{ 61, "Open file" },
	{ 62, "Close file" },
	{ 63, "Read file" },
	{ 64, "Write to file" },
	{ 65, "Delete file" },
	{ 66, "Seek file pointer" },
	{ 67, "Get/set file attributes" },
	{ 68, "Extended allocate memory" },
	{ 69, "Duplicate file handle" },
	{ 70, "Force file handle" },
	{ 71, "Get current directory" },
	{ 72, "Allocate memory" },
	{ 73, "Release memory" },
	{ 74, "Shrink allocated block" },
	{ 75, "Load/execute process" },
	{ 76, "Terminate process" },
	{ 78, "Search first" },
	{ 79, "Search next" },
	{ 86, "Rename file" },
	{ 87, "Get/set file timestamp" },
	{ 92, "" },
	{ 96, "" },
	{ 98, "" },
	{ 99, "" },
	{ 100, "" },
	{ 101, "" },
	{ 102, "" },
	{ 255, "(MiNT)" },
	{ 256, "(MiNT)" },
	{ 257, "(MiNT)" },
	{ 258, "(MiNT)" },
	{ 259, "(MiNT)" },
	{ 260, "(MiNT)" },
	{ 261, "(MiNT)" },
	{ 262, "(MiNT)" },
	{ 263, "(MiNT)" },
	{ 264, "(MiNT)" },
	{ 265, "(MiNT)" },
	{ 266, "(MiNT)" },
	{ 267, "(MiNT)" },
	{ 268, "(MiNT)" },
	{ 269, "(MiNT)" },
	{ 270, "(MiNT)" },
	{ 271, "(MiNT)" },
	{ 272, "(MiNT)" },
	{ 273, "(MiNT)" },
	{ 274, "(MiNT)" },
	{ 275, "(MiNT)" },
	{ 276, "(MiNT)" },
	{ 277, "(MiNT)" },
	{ 278, "(MiNT)" },
	{ 279, "(MiNT)" },
	{ 280, "(MiNT)" },
	{ 281, "(MiNT)" },
	{ 282, "(MiNT)" },
	{ 283, "(MiNT)" },
	{ 284, "(MiNT)" },
	{ 285, "(MiNT)" },
	{ 286, "(MiNT)" },
	{ 287, "(MiNT)" },
	{ 288, "(MiNT)" },
	{ 289, "(MiNT)" },
	{ 290, "(MiNT)" },
	{ 291, "MiNT" },
	{ 292, "(MiNT)" },
	{ 293, "(MiNT)" },
	{ 294, "(MiNT)" },
	{ 295, "(MiNT)" },
	{ 296, "(MiNT)" },
	{ 297, "(MiNT)" },
	{ 298, "(MiNT)" },
	{ 299, "(MiNT)" },
	{ 300, "(MiNT)" },
	{ 301, "(MiNT)" },
	{ 302, "(MiNT)" },
	{ 303, "(MiNT)" },
	{ 304, "(MiNT)" },
	{ 305, "(MiNT)" },
	{ 306, "(MiNT)" },
	{ 307, "(MiNT)" },
	{ 308, "(MiNT)" },
	{ 309, "(MiNT)" },
	{ 310, "(MiNT)" },
	{ 311, "(MiNT)" },
	{ 312, "(MiNT)" },
	{ 313, "(MiNT)" },
	{ 314, "(MiNT)" },
	{ 315, "(MiNT)" },
	{ 316, "(MiNT)" },
	{ 317, "(MiNT 1.10)" },
	{ 318, "(MiNT 1.11 until FreeMiNT 1.15.12 inclusive)" },
	{ 319, "(MiNT 1.11)" },
	{ 320, "(MiNT)" },
	{ 321, "(MiNT)" },
	{ 322, "(MiNT 1.11)" },
	{ 323, "(MiNT 1.11)" },
	{ 324, "(MiNT 1.11)" },
	{ 325, "(MiNT 1.11)" },
	{ 326, "(MiNT 1.11)" },
	{ 327, "(MiNT 1.11)" },
	{ 328, "(MiNT 1.11)" },
	{ 329, "(MiNT 1.11)" },
	{ 330, "(MiNT (obsolete))" },
	{ 331, "(MiNT)" },
	{ 332, "(MiNT)" },
	{ 333, "(MiNT)" },
	{ 334, "(MiNT 1.12)" },
	{ 335, "(MiNT 1.12)" },
	{ 336, "(MiNT, MagiC)" },
	{ 337, "(MiNT)" },
	{ 338, "(MiNT 1.12)" },
	{ 339, "MiNT 1.12" },
	{ 340, "(MiNT 1.15.0)" },
	{ 341, "(MiNT 1.15.0)" },
	{ 342, "(MiNT 1.15.0)" },
	{ 343, "(MiNT)" },
	{ 344, "(MiNT 1.15.0)" },
	{ 345, "(MiNT 1.15.0)" },
	{ 346, "(MiNTNet)" },
	{ 347, "(MiNTNet)" },
	{ 348, "(MiNTNet)" },
	{ 349, "(MiNTNet)" },
	{ 350, "(MiNT)" },
	{ 351, "(MiNT)" },
	{ 352, "(MiNTNet)" },
	{ 353, "(MiNTNet)" },
	{ 354, "(MiNTNet)" },
	{ 355, "(MiNTNet)" },
	{ 356, "(MiNTNet)" },
	{ 357, "(MiNTNet)" },
	{ 358, "(MiNTNet)" },
	{ 359, "(MiNTNet)" },
	{ 360, "(MiNTNet)" },
	{ 361, "(MiNTNet)" },
	{ 362, "(MiNTNet)" },
	{ 363, "(MiNTNet)" },
	{ 364, "(MiNTNet)" },
	{ 365, "(MiNTNet)" },
	{ 366, "(MiNTNet)" },
	{ 368, "(MiNT)" },
	{ 369, "(MiNT)" },
	{ 370, "(MiNT)" },
	{ 371, "(MiNT)" },
	{ 372, "(MiNT)" },
	{ 373, "(MiNT)" },
	{ 374, "(MiNT)" },
	{ 375, "(MiNT)" },
	{ 376, "(MiNT)" },
	{ 377, "(MiNT)" },
	{ 378, "(MiNT)" },
	{ 379, "(MiNT)" },
	{ 381, "(MiNT)" },
	{ 384, "(FreeMiNT 1.16.0)" },
	{ 385, "(FreeMiNT 1.17)" },
	{ 386, "(FreeMiNT 1.17)" },
	{ 387, "(FreeMiNT 1.17)" },
	{ 0, nullptr }
};
/* Register Field Sets */

} // namespace
