/* Autogenerated file */


#ifndef STGEN_xbios_H
#define STGEN_xbios_H
#include <stdint.h>

#include "stgen.h"

namespace Xbios {


/* Enum Opcode */
enum class Opcode : uint32_t {
	Initmouse            =      0, /* Initialize mouse pointer */
	Ssbrk                =      1, /*  */
	Physbase             =      2, /* Get physical screen base */
	Logbase              =      3, /* Get logical screen base */
	Getrez               =      4, /* Get screen resolution */
	Setscreen            =      5, /* Set screen resolution, base addresses */
	Setpalette           =      6, /* Set colour palette */
	Setcolor             =      7, /* Set single colour */
	Floprd               =      8, /* Read floppy disk sectors */
	Flopwr               =      9, /* Write floppy disk sectors */
	Flopfmt              =     10, /* Format floppy disk track */
	Midiws               =     12, /*  */
	Mfpint               =     13, /*  */
	Iorec                =     14, /*  */
	Rsconf               =     15, /*  */
	Keytbl               =     16, /*  */
	Random               =     17, /*  */
	Protobt              =     18, /* Generate floppy boot sector */
	Flopver              =     19, /* Verify floppy disk sectors */
	Scrdmp               =     20, /* Print screen dump */
	Cursconf             =     21, /*  */
	Settime              =     22, /* Set time and date */
	Gettime              =     23, /* Get time and date */
	Bioskeys             =     24, /*  */
	Ikbdws               =     25, /*  */
	Jdisint              =     26, /*  */
	Jenabint             =     27, /*  */
	Giaccess             =     28, /*  */
	Offgibit             =     29, /*  */
	Ongibit              =     30, /*  */
	Xbtimer              =     31, /* Set MFP timer */
	Dosound              =     32, /*  */
	Setprt               =     33, /* Set/get printer settings */
	Kbdvbase             =     34, /*  */
	Kbrate               =     35, /*  */
	Prtblk               =     36, /* Print parameter block */
	Vsync                =     37, /*  */
	Supexec              =     38, /* Call routine in Supervisor Mode */
	Puntaes              =     39, /*  */
	Floprate             =     41, /* Set floppy drive seekrate and timeout (TOS 1.04) */
	DMAread              =     42, /* Read HDD sectors */
	DMAwrite             =     43, /* Writefabi HDD sectors */
	Bconmap              =     44, /* TOS 2 */
	NVMaccess            =     46, /* Read/write non-volatile RAM (TOS 3+) */
	Waketime             =     47, /* (TOS 2.06, ST-Book) */
	Blitmode             =     64, /*  */
	EsetPalette          =     84, /*  */
	EgetPalette          =     85, /*  */
	EsetGray             =     86, /*  */
	EsetSmear            =     87, /*  */
	Vsetmode             =     88, /* (Falcon) */
	VgetMonitor          =     89, /* (Falcon) */
	VsetSync             =     90, /* (Falcon) */
	VgetSize             =     91, /* (Falcon) */
	VsetVars             =     92, /* (Falcon) */
	VsetRGB              =     93, /* (Falcon) */
	VgetRGB              =     94, /* (Falcon) */
	VcheckMode           =     95, /* (Falcon), MilanTOS */
	Dsp_DoBlock          =     96, /* Transfer data block (Falcon) */
	Dsp_BlkHandShake     =     97, /* Transfer handshaked (Falcon) */
	Dsp_BlkUnpacked      =     98, /* (Falcon) */
	Dsp_InStream         =     99, /* (Falcon) */
	Dsp_OutStream        =    100, /* (Falcon) */
	Dsp_IOStream         =    101, /* (Falcon) */
	Dsp_RemoveInterrupts =    102, /* (Falcon) */
	Dsp_GetWordSize      =    103, /* Get DSP word size (Falcon) */
	Dsp_Lock             =    104, /* (Falcon) */
	Dsp_Unlock           =    105, /* (Falcon) */
	Dsp_Available        =    106, /* Get DSP free memory (Falcon) */
	Dsp_Reserve          =    107, /* (Falcon) */
	Dsp_LoadProg         =    108, /* (Falcon) */
	Dsp_ExecProg         =    109, /* Execute DSP program (Falcon) */
	Dsp_ExecBoot         =    110, /* Load DSP boot program (Falcon) */
	Dsp_LodToBinary      =    111, /* (Falcon) */
	Dsp_TriggerHC        =    112, /* (Falcon) */
	Dsp_RequestUniqueAbility =    113, /* (Falcon) */
	Dsp_GetProgAbility   =    114, /* Request program identification (Falcon) */
	Dsp_FlushSubroutines =    115, /* Remove DSP subroutines (Falcon) */
	Dsp_LoadSubroutine   =    116, /* (Falcon) */
	Dsp_InqSubrAbility   =    117, /* (Falcon) */
	Dsp_RunSubroutine    =    118, /* (Falcon) */
	Dsp_Hf0              =    119, /* (Falcon) */
	Dsp_Hf1              =    120, /* (Falcon) */
	Dsp_Hf2              =    121, /* (Falcon) */
	Dsp_Hf3              =    122, /* (Falcon) */
	Dsp_BlkWords         =    123, /* Transfer DSP word data (Falcon) */
	Dsp_BlkBytes         =    124, /* Transfer DSP byte data (Falcon) */
	Dsp_HStat            =    125, /* (Falcon) */
	Dsp_SetVectors       =    126, /* (Falcon) */
	Dsp_MultBlocks       =    127, /* (Falcon) */
	locksnd              =    128, /* (Falcon) */
	unlocksnd            =    129, /* (Falcon) */
	soundcmd             =    130, /* (Falcon) */
	setbuffer            =    131, /* (Falcon) */
	setmode              =    132, /* (Falcon) */
	settracks            =    133, /* (Falcon) */
	setmontracks         =    134, /* (Falcon) */
	setinterrupt         =    135, /* (Falcon) */
	buffoper             =    136, /* (Falcon) */
	dsptristate          =    137, /* (Falcon) */
	gpio                 =    138, /* (Falcon) */
	devconnect           =    139, /* (Falcon) */
	sndstatus            =    140, /* (Falcon) */
	buffptr              =    141, /* (Falcon) */
	VsetMask             =    150  /*  */
};

/* Enum -> string lookup declarations */
extern const char* GetString(Opcode val);
extern const char* GetEnumString(Opcode val);

/* Register Addresses */

/* Register Field Accessors */

/* Register Field Sets */

} // namespace
#endif
