/* Autogenerated file */

#include "xbios.h"

namespace Xbios {

const char* GetString(Opcode val)
{
	if (val==Opcode::Initmouse) return "Initialize mouse pointer";
	if (val==Opcode::Ssbrk) return "";
	if (val==Opcode::Physbase) return "Get physical screen base";
	if (val==Opcode::Logbase) return "Get logical screen base";
	if (val==Opcode::Getrez) return "Get screen resolution";
	if (val==Opcode::Setscreen) return "Set screen resolution, base addresses";
	if (val==Opcode::Setpalette) return "Set colour palette";
	if (val==Opcode::Setcolor) return "Set single colour";
	if (val==Opcode::Floprd) return "";
	if (val==Opcode::Flopwr) return "";
	if (val==Opcode::Flopfmt) return "";
	if (val==Opcode::Dbmsg) return "Atari Debugger";
	if (val==Opcode::Midiws) return "";
	if (val==Opcode::Mfpint) return "";
	if (val==Opcode::Iorec) return "";
	if (val==Opcode::Rsconf) return "";
	if (val==Opcode::Keytbl) return "";
	if (val==Opcode::Random) return "";
	if (val==Opcode::Protobt) return "";
	if (val==Opcode::Flopver) return "";
	if (val==Opcode::Scrdmp) return "";
	if (val==Opcode::Cursconf) return "";
	if (val==Opcode::Settime) return "";
	if (val==Opcode::Gettime) return "";
	if (val==Opcode::Bioskeys) return "";
	if (val==Opcode::Ikbdws) return "";
	if (val==Opcode::Jdisint) return "";
	if (val==Opcode::Jenabint) return "";
	if (val==Opcode::Giaccess) return "";
	if (val==Opcode::Offgibit) return "";
	if (val==Opcode::Ongibit) return "";
	if (val==Opcode::Xbtimer) return "";
	if (val==Opcode::Dosound) return "";
	if (val==Opcode::Setprt) return "";
	if (val==Opcode::Kbdvbase) return "";
	if (val==Opcode::Kbrate) return "";
	if (val==Opcode::Prtblk) return "";
	if (val==Opcode::Vsync) return "";
	if (val==Opcode::Supexec) return "";
	if (val==Opcode::Puntaes) return "";
	if (val==Opcode::Floprate) return "TOS 1.04";
	if (val==Opcode::DMAread) return "";
	if (val==Opcode::DMAwrite) return "";
	if (val==Opcode::Bconmap) return "TOS 2";
	if (val==Opcode::NVMaccess) return "TOS 3";
	if (val==Opcode::Waketime) return "TOS 2.06, ST-Book";
	if (val==Opcode::Blitmode) return "";
	if (val==Opcode::EsetPalette) return "";
	if (val==Opcode::EgetPalette) return "";
	if (val==Opcode::EsetGray) return "";
	if (val==Opcode::EsetSmear) return "";
	if (val==Opcode::Vsetmode) return "(Falcon)";
	if (val==Opcode::VgetMonitor) return "(Falcon)";
	if (val==Opcode::VsetSync) return "(Falcon)";
	if (val==Opcode::VgetSize) return "(Falcon)";
	if (val==Opcode::VsetVars) return "(Falcon)";
	if (val==Opcode::VsetRGB) return "(Falcon)";
	if (val==Opcode::VgetRGB) return "(Falcon)";
	if (val==Opcode::VcheckMode) return "(Falcon), MilanTOS";
	if (val==Opcode::Dsp_DoBlock) return "(Falcon)";
	if (val==Opcode::Dsp_BlkHandShake) return "(Falcon)";
	if (val==Opcode::Dsp_BlkUnpacked) return "(Falcon)";
	if (val==Opcode::Dsp_InStream) return "(Falcon)";
	if (val==Opcode::Dsp_OutStream) return "(Falcon)";
	if (val==Opcode::Dsp_IOStream) return "(Falcon)";
	if (val==Opcode::Dsp_RemoveInterrupts) return "(Falcon)";
	if (val==Opcode::Dsp_GetWordSize) return "(Falcon)";
	if (val==Opcode::Dsp_Lock) return "(Falcon)";
	if (val==Opcode::Dsp_Unlock) return "(Falcon)";
	if (val==Opcode::Dsp_Available) return "(Falcon)";
	if (val==Opcode::Dsp_Reserve) return "(Falcon)";
	if (val==Opcode::Dsp_LoadProg) return "(Falcon)";
	if (val==Opcode::Dsp_ExecProg) return "(Falcon)";
	if (val==Opcode::Dsp_ExecBoot) return "(Falcon)";
	if (val==Opcode::Dsp_LodToBinary) return "(Falcon)";
	if (val==Opcode::Dsp_TriggerHC) return "(Falcon)";
	if (val==Opcode::Dsp_RequestUniqueAbility) return "(Falcon)";
	if (val==Opcode::Dsp_GetProgAbility) return "(Falcon)";
	if (val==Opcode::Dsp_FlushSubroutines) return "(Falcon)";
	if (val==Opcode::Dsp_LoadSubroutine) return "(Falcon)";
	if (val==Opcode::Dsp_InqSubrAbility) return "(Falcon)";
	if (val==Opcode::Dsp_RunSubroutine) return "(Falcon)";
	if (val==Opcode::Dsp_Hf0) return "(Falcon)";
	if (val==Opcode::Dsp_Hf1) return "(Falcon)";
	if (val==Opcode::Dsp_Hf2) return "(Falcon)";
	if (val==Opcode::Dsp_Hf3) return "(Falcon)";
	if (val==Opcode::Dsp_BlkWords) return "(Falcon)";
	if (val==Opcode::Dsp_BlkBytes) return "(Falcon)";
	if (val==Opcode::Dsp_HStat) return "(Falcon)";
	if (val==Opcode::Dsp_SetVectors) return "(Falcon)";
	if (val==Opcode::Dsp_MultBlocks) return "(Falcon)";
	if (val==Opcode::locksnd) return "(Falcon)";
	if (val==Opcode::unlocksnd) return "(Falcon)";
	if (val==Opcode::soundcmd) return "(Falcon)";
	if (val==Opcode::setbuffer) return "(Falcon)";
	if (val==Opcode::setmode) return "(Falcon)";
	if (val==Opcode::settracks) return "(Falcon)";
	if (val==Opcode::setmontracks) return "(Falcon)";
	if (val==Opcode::setinterrupt) return "(Falcon)";
	if (val==Opcode::buffoper) return "(Falcon)";
	if (val==Opcode::dsptristate) return "(Falcon)";
	if (val==Opcode::gpio) return "(Falcon)";
	if (val==Opcode::devconnect) return "(Falcon)";
	if (val==Opcode::sndstatus) return "(Falcon)";
	if (val==Opcode::buffptr) return "(Falcon)";
	if (val==Opcode::VsetMask) return "";
	return "?";
}
const char* GetEnumString(Opcode val)
{
	if (val==Opcode::Initmouse) return "Initmouse";
	if (val==Opcode::Ssbrk) return "Ssbrk";
	if (val==Opcode::Physbase) return "Physbase";
	if (val==Opcode::Logbase) return "Logbase";
	if (val==Opcode::Getrez) return "Getrez";
	if (val==Opcode::Setscreen) return "Setscreen";
	if (val==Opcode::Setpalette) return "Setpalette";
	if (val==Opcode::Setcolor) return "Setcolor";
	if (val==Opcode::Floprd) return "Floprd";
	if (val==Opcode::Flopwr) return "Flopwr";
	if (val==Opcode::Flopfmt) return "Flopfmt";
	if (val==Opcode::Dbmsg) return "Dbmsg";
	if (val==Opcode::Midiws) return "Midiws";
	if (val==Opcode::Mfpint) return "Mfpint";
	if (val==Opcode::Iorec) return "Iorec";
	if (val==Opcode::Rsconf) return "Rsconf";
	if (val==Opcode::Keytbl) return "Keytbl";
	if (val==Opcode::Random) return "Random";
	if (val==Opcode::Protobt) return "Protobt";
	if (val==Opcode::Flopver) return "Flopver";
	if (val==Opcode::Scrdmp) return "Scrdmp";
	if (val==Opcode::Cursconf) return "Cursconf";
	if (val==Opcode::Settime) return "Settime";
	if (val==Opcode::Gettime) return "Gettime";
	if (val==Opcode::Bioskeys) return "Bioskeys";
	if (val==Opcode::Ikbdws) return "Ikbdws";
	if (val==Opcode::Jdisint) return "Jdisint";
	if (val==Opcode::Jenabint) return "Jenabint";
	if (val==Opcode::Giaccess) return "Giaccess";
	if (val==Opcode::Offgibit) return "Offgibit";
	if (val==Opcode::Ongibit) return "Ongibit";
	if (val==Opcode::Xbtimer) return "Xbtimer";
	if (val==Opcode::Dosound) return "Dosound";
	if (val==Opcode::Setprt) return "Setprt";
	if (val==Opcode::Kbdvbase) return "Kbdvbase";
	if (val==Opcode::Kbrate) return "Kbrate";
	if (val==Opcode::Prtblk) return "Prtblk";
	if (val==Opcode::Vsync) return "Vsync";
	if (val==Opcode::Supexec) return "Supexec";
	if (val==Opcode::Puntaes) return "Puntaes";
	if (val==Opcode::Floprate) return "Floprate";
	if (val==Opcode::DMAread) return "DMAread";
	if (val==Opcode::DMAwrite) return "DMAwrite";
	if (val==Opcode::Bconmap) return "Bconmap";
	if (val==Opcode::NVMaccess) return "NVMaccess";
	if (val==Opcode::Waketime) return "Waketime";
	if (val==Opcode::Blitmode) return "Blitmode";
	if (val==Opcode::EsetPalette) return "EsetPalette";
	if (val==Opcode::EgetPalette) return "EgetPalette";
	if (val==Opcode::EsetGray) return "EsetGray";
	if (val==Opcode::EsetSmear) return "EsetSmear";
	if (val==Opcode::Vsetmode) return "Vsetmode";
	if (val==Opcode::VgetMonitor) return "VgetMonitor";
	if (val==Opcode::VsetSync) return "VsetSync";
	if (val==Opcode::VgetSize) return "VgetSize";
	if (val==Opcode::VsetVars) return "VsetVars";
	if (val==Opcode::VsetRGB) return "VsetRGB";
	if (val==Opcode::VgetRGB) return "VgetRGB";
	if (val==Opcode::VcheckMode) return "VcheckMode";
	if (val==Opcode::Dsp_DoBlock) return "Dsp_DoBlock";
	if (val==Opcode::Dsp_BlkHandShake) return "Dsp_BlkHandShake";
	if (val==Opcode::Dsp_BlkUnpacked) return "Dsp_BlkUnpacked";
	if (val==Opcode::Dsp_InStream) return "Dsp_InStream";
	if (val==Opcode::Dsp_OutStream) return "Dsp_OutStream";
	if (val==Opcode::Dsp_IOStream) return "Dsp_IOStream";
	if (val==Opcode::Dsp_RemoveInterrupts) return "Dsp_RemoveInterrupts";
	if (val==Opcode::Dsp_GetWordSize) return "Dsp_GetWordSize";
	if (val==Opcode::Dsp_Lock) return "Dsp_Lock";
	if (val==Opcode::Dsp_Unlock) return "Dsp_Unlock";
	if (val==Opcode::Dsp_Available) return "Dsp_Available";
	if (val==Opcode::Dsp_Reserve) return "Dsp_Reserve";
	if (val==Opcode::Dsp_LoadProg) return "Dsp_LoadProg";
	if (val==Opcode::Dsp_ExecProg) return "Dsp_ExecProg";
	if (val==Opcode::Dsp_ExecBoot) return "Dsp_ExecBoot";
	if (val==Opcode::Dsp_LodToBinary) return "Dsp_LodToBinary";
	if (val==Opcode::Dsp_TriggerHC) return "Dsp_TriggerHC";
	if (val==Opcode::Dsp_RequestUniqueAbility) return "Dsp_RequestUniqueAbility";
	if (val==Opcode::Dsp_GetProgAbility) return "Dsp_GetProgAbility";
	if (val==Opcode::Dsp_FlushSubroutines) return "Dsp_FlushSubroutines";
	if (val==Opcode::Dsp_LoadSubroutine) return "Dsp_LoadSubroutine";
	if (val==Opcode::Dsp_InqSubrAbility) return "Dsp_InqSubrAbility";
	if (val==Opcode::Dsp_RunSubroutine) return "Dsp_RunSubroutine";
	if (val==Opcode::Dsp_Hf0) return "Dsp_Hf0";
	if (val==Opcode::Dsp_Hf1) return "Dsp_Hf1";
	if (val==Opcode::Dsp_Hf2) return "Dsp_Hf2";
	if (val==Opcode::Dsp_Hf3) return "Dsp_Hf3";
	if (val==Opcode::Dsp_BlkWords) return "Dsp_BlkWords";
	if (val==Opcode::Dsp_BlkBytes) return "Dsp_BlkBytes";
	if (val==Opcode::Dsp_HStat) return "Dsp_HStat";
	if (val==Opcode::Dsp_SetVectors) return "Dsp_SetVectors";
	if (val==Opcode::Dsp_MultBlocks) return "Dsp_MultBlocks";
	if (val==Opcode::locksnd) return "locksnd";
	if (val==Opcode::unlocksnd) return "unlocksnd";
	if (val==Opcode::soundcmd) return "soundcmd";
	if (val==Opcode::setbuffer) return "setbuffer";
	if (val==Opcode::setmode) return "setmode";
	if (val==Opcode::settracks) return "settracks";
	if (val==Opcode::setmontracks) return "setmontracks";
	if (val==Opcode::setinterrupt) return "setinterrupt";
	if (val==Opcode::buffoper) return "buffoper";
	if (val==Opcode::dsptristate) return "dsptristate";
	if (val==Opcode::gpio) return "gpio";
	if (val==Opcode::devconnect) return "devconnect";
	if (val==Opcode::sndstatus) return "sndstatus";
	if (val==Opcode::buffptr) return "buffptr";
	if (val==Opcode::VsetMask) return "VsetMask";
	return "?";
}
const stgen::StringDef g_enumDescs_Opcode[] = {
	{ 0, "Initialize mouse pointer" },
	{ 1, "" },
	{ 2, "Get physical screen base" },
	{ 3, "Get logical screen base" },
	{ 4, "Get screen resolution" },
	{ 5, "Set screen resolution, base addresses" },
	{ 6, "Set colour palette" },
	{ 7, "Set single colour" },
	{ 8, "" },
	{ 9, "" },
	{ 10, "" },
	{ 11, "Atari Debugger" },
	{ 12, "" },
	{ 13, "" },
	{ 14, "" },
	{ 15, "" },
	{ 16, "" },
	{ 17, "" },
	{ 18, "" },
	{ 19, "" },
	{ 20, "" },
	{ 21, "" },
	{ 22, "" },
	{ 23, "" },
	{ 24, "" },
	{ 25, "" },
	{ 26, "" },
	{ 27, "" },
	{ 28, "" },
	{ 29, "" },
	{ 30, "" },
	{ 31, "" },
	{ 32, "" },
	{ 33, "" },
	{ 34, "" },
	{ 35, "" },
	{ 36, "" },
	{ 37, "" },
	{ 38, "" },
	{ 39, "" },
	{ 41, "TOS 1.04" },
	{ 42, "" },
	{ 43, "" },
	{ 44, "TOS 2" },
	{ 46, "TOS 3" },
	{ 47, "TOS 2.06, ST-Book" },
	{ 64, "" },
	{ 84, "" },
	{ 85, "" },
	{ 86, "" },
	{ 87, "" },
	{ 88, "(Falcon)" },
	{ 89, "(Falcon)" },
	{ 90, "(Falcon)" },
	{ 91, "(Falcon)" },
	{ 92, "(Falcon)" },
	{ 93, "(Falcon)" },
	{ 94, "(Falcon)" },
	{ 95, "(Falcon), MilanTOS" },
	{ 96, "(Falcon)" },
	{ 97, "(Falcon)" },
	{ 98, "(Falcon)" },
	{ 99, "(Falcon)" },
	{ 100, "(Falcon)" },
	{ 101, "(Falcon)" },
	{ 102, "(Falcon)" },
	{ 103, "(Falcon)" },
	{ 104, "(Falcon)" },
	{ 105, "(Falcon)" },
	{ 106, "(Falcon)" },
	{ 107, "(Falcon)" },
	{ 108, "(Falcon)" },
	{ 109, "(Falcon)" },
	{ 110, "(Falcon)" },
	{ 111, "(Falcon)" },
	{ 112, "(Falcon)" },
	{ 113, "(Falcon)" },
	{ 114, "(Falcon)" },
	{ 115, "(Falcon)" },
	{ 116, "(Falcon)" },
	{ 117, "(Falcon)" },
	{ 118, "(Falcon)" },
	{ 119, "(Falcon)" },
	{ 120, "(Falcon)" },
	{ 121, "(Falcon)" },
	{ 122, "(Falcon)" },
	{ 123, "(Falcon)" },
	{ 124, "(Falcon)" },
	{ 125, "(Falcon)" },
	{ 126, "(Falcon)" },
	{ 127, "(Falcon)" },
	{ 128, "(Falcon)" },
	{ 129, "(Falcon)" },
	{ 130, "(Falcon)" },
	{ 131, "(Falcon)" },
	{ 132, "(Falcon)" },
	{ 133, "(Falcon)" },
	{ 134, "(Falcon)" },
	{ 135, "(Falcon)" },
	{ 136, "(Falcon)" },
	{ 137, "(Falcon)" },
	{ 138, "(Falcon)" },
	{ 139, "(Falcon)" },
	{ 140, "(Falcon)" },
	{ 141, "(Falcon)" },
	{ 150, "" },
	{ 0, nullptr }
};
/* Register Field Sets */

} // namespace
