#ifndef FONDA_LIB_DWARF_STRUCT_H
#define FONDA_LIB_DWARF_STRUCT_H
#include <stdint.h>

#define DW_TAG_array_type 0x01
#define DW_TAG_class_type 0x02
#define DW_TAG_entry_point 0x03
#define DW_TAG_enumeration_type 0x04
#define DW_TAG_formal_parameter 0x05
#define DW_TAG_imported_declaration 0x08
#define DW_TAG_label 0x0a
#define DW_TAG_lexical_block 0x0b
#define DW_TAG_member 0x0d
#define DW_TAG_pointer_type 0x0f
#define DW_TAG_reference_type 0x10
#define DW_TAG_compile_unit 0x11
#define DW_TAG_string_type 0x12
#define DW_TAG_structure_type 0x13
#define DW_TAG_subroutine_type 0x15
#define DW_TAG_typedef 0x16
#define DW_TAG_union_type 0x17
#define DW_TAG_unspecified_parameters 0x18
#define DW_TAG_variant 0x19
#define DW_TAG_common_block 0x1a
#define DW_TAG_common_inclusion 0x1b
#define DW_TAG_inheritance 0x1c
#define DW_TAG_inlined_subroutine 0x1d
#define DW_TAG_module 0x1e
#define DW_TAG_ptr_to_member_type 0x1f
#define DW_TAG_set_type 0x20
#define DW_TAG_subrange_type 0x21
#define DW_TAG_with_stmt 0x22
#define DW_TAG_access_declaration 0x23
#define DW_TAG_base_type 0x24
#define DW_TAG_catch_block 0x25
#define DW_TAG_const_type 0x26
#define DW_TAG_constant 0x27
#define DW_TAG_enumerator 0x28
#define DW_TAG_file_type 0x29
#define DW_TAG_friend 0x2a
#define DW_TAG_namelist 0x2b
#define DW_TAG_namelist_item 0x2c
#define DW_TAG_packed_type 0x2d
#define DW_TAG_subprogram 0x2e
#define DW_TAG_template_type_parameter 0x2f
#define DW_TAG_template_value_parameter 0x30
#define DW_TAG_thrown_type 0x31
#define DW_TAG_try_block 0x32
#define DW_TAG_variant_part 0x33
#define DW_TAG_variable 0x34
#define DW_TAG_volatile_type 0x35
#define DW_TAG_dwarf_procedure 0x36
#define DW_TAG_restrict_type 0x37
#define DW_TAG_interface_type 0x38
#define DW_TAG_namespace 0x39
#define DW_TAG_imported_module 0x3a
#define DW_TAG_unspecified_type 0x3b
#define DW_TAG_partial_unit 0x3c
#define DW_TAG_imported_unit 0x3d
#define DW_TAG_condition 0x3f
#define DW_TAG_shared_type 0x40
#define DW_TAG_lo_user 0x4080
#define DW_TAG_hi_user 0xffff

/* statement machine opcodes */
#define DW_LNS_copy             1
#define DW_LNS_advance_pc       2
#define DW_LNS_advance_line     3
#define DW_LNS_set_file         4
#define DW_LNS_set_column       5
#define DW_LNS_negate_stmt		6
#define DW_LNS_const_add_pc     8

#define DW_LNE_end_sequence      1
#define DW_LNE_set_address       2
#define DW_LNE_define_file		 3
#define DW_LNE_set_discriminator 4

#define DW_LNCT_path			1
#define DW_LNCT_directory_index	2
#define DW_LNCT_timestamp		3
#define DW_LNCT_size			4
#define DW_LNCT_MD5				5

#define DW_FORM_addr	1	
#define DW_FORM_block2	3	
#define DW_FORM_block4	4	
#define DW_FORM_data2	5	
#define DW_FORM_data4	6	
#define DW_FORM_data8	7	
#define DW_FORM_string	8	
#define DW_FORM_block	9	
#define DW_FORM_block1	10	
#define DW_FORM_data1	11	
#define DW_FORM_flag	12	
#define DW_FORM_sdata	13	
#define DW_FORM_strp	14	
#define DW_FORM_udata	15	
#define DW_FORM_ref_addr	16	
#define DW_FORM_ref1	17	
#define DW_FORM_ref2	18	
#define DW_FORM_ref4	19	
#define DW_FORM_ref8	20	
#define DW_FORM_ref_udata	21	
#define DW_FORM_indirect	22	
#define DW_FORM_sec_offset	23	
#define DW_FORM_exprloc	24	
#define DW_FORM_flag_present	25	
#define DW_FORM_ref_sig8	32	
#define DW_FORM_strx	26	
#define DW_FORM_addrx	27	
#define DW_FORM_ref_sup4	28	
#define DW_FORM_strp_sup	29	
#define DW_FORM_data16	30	
#define DW_FORM_line_strp	31	
#define DW_FORM_implicit_const	33	
#define DW_FORM_loclistx	34	
#define DW_FORM_rnglistx	35	
#define DW_FORM_ref_sup8	36	
#define DW_FORM_strx1	37	
#define DW_FORM_strx2	38	
#define DW_FORM_strx3	39	
#define DW_FORM_strx4	40	
#define DW_FORM_addrx1	41	
#define DW_FORM_addrx2	42	
#define DW_FORM_addrx3	43	
#define DW_FORM_addrx4	44

#endif // FONDA_LIB_DWARF_STRUCT_H
