[Bindings]
; Main window bindings
startStop="Ctrl+R"
startStop2="F5"
break="Esc"
step="S"
step2="F11"
stepDsp="Shift+S"
skip="Ctrl+S"
next="N"
next2="F10"
nextDsp="Shift+N"
until="U"
untilCycle="Ctrl+Shift+U"
untilRts="Ctrl+U,S"
untilRte="Ctrl+U,E"
untilVbl="Ctrl+U,V"
untilHbl="Ctrl+U,H"
untilRam="Ctrl+U,R"

; Shared bindings across some windows
contextMenu="Ctrl+Space"

; Window focus selection
launch="Alt+L"
quicklaunch="Alt+Q"

focusDisasm1="Alt+D"
focusDisasm2="Alt+Shift+D"
focusMemory1="Alt+M"
focusMemory2="Alt+2"
focusMemory3="Alt+3"
focusMemory4="Alt+4"
focusGraphics="Alt+G"
focusBreakpoints="Alt+B"
focusRegisters="Alt+R"
focusConsole="Alt+C"
focusHardware="Alt+H"
focusProfile="Alt+P"

; Disassembly window
toggleBreakpoint="F9"
addbreakpoint="Ctrl+Shift+B"
runToCursor="Ctrl+H"
runToCursor2="Ctrl+F10"
disasmFind="Ctrl+F"
disasmFindNext="F3"
disasmGoto="Ctrl+G"
disasmLock="Ctrl+L"

; Graphics Inspector
graphicsGoto="Ctrl+G"
graphicsLock="Ctrl+L"

; Memory Windows
memoryFind="Ctrl+F"
memoryFindNext="F3"
memoryGoto="Ctrl+G"
memoryLock="Ctrl+L"
memoryWrite="Ctrl+W"

